### ISSUE TITLE
Example of Manual Conversion

### ISSUE THREAD

**Issue by darkfrog26** [konsoletyper/teavm#106]
I'm interested in using TeaVM, but I don't want to use Maven or Eclipse to do it.  It would be greatly appreciated if there was some explanation of how to accomplish this manually either command-line or programatically.

Also, I'd like to try to test this using Scala as the source language and I see no mention of this anywhere. Has this been tried?

**Comment by konsoletyper** [comment]
Why don't you want to use Maven? There is no (documented) way to run TeaVM manually. You can take a look at `teavm-cli`, but no documentation available. If you prefer another build system, like Gradle or SBT, you can create your own build plugin for TeaVM. Just take a look at Maven plugin implementation. It should be fairly easy, since TeaVMTool does all work.

I tried Scala and failed. There was nothing special in bytecode produced by Scala, but Scala standard library relies on classloader, reflection and other things that are not yet implemented (and won't be ever implemented) in TeaVM. Also I don't know about Scala support of Invokedynamic. If recent versions of Scala emit this instruction, TeaVM will fail again, since it does not support Invokedynamic (and won't ever support it completely). I guess if someone forked or patched Scala library for TeaVM, it could be possible to run Scala in JavaScript. What about Scala.js? Do they maintain their own version of Scala library? Is it possible to borrow this library to create TeaVM Scala port?

**Comment by konsoletyper** [comment]
BTW, I've just successfully compiled Kotlin application, see [live example](http://teavm.org/live-examples/kotlin/index.html) and [project sources](https://github.com/konsoletyper/teavm/tree/master/teavm-samples/teavm-samples-kotlin)

**Comment by darkfrog26** [comment]
I want to use SBT ideally.  Unless you're doing something specific (like using Dynamic or duck typing) Scala shouldn't be doing anything with invokedynamic at all.  Regarding Scala.js it very well might be possible to utilize it as it is an open-source project and already provides much of what you would need.

I'll look into trying a basic example and get back to you.

**Comment by konsoletyper** [comment]
Scala might, as well as Java 8 compiler, use InvokeDynamic for lambdas. Not to reproduce some dynamically typed behaviour, but simply reduce number of generated classes, as call sites are much more lightweight than classes.

**Comment by darkfrog26** [comment]
That's a possibility, but if that's the case then Scala.js would be an ideal solution to help resolve it.

**Comment by sjrd** [comment]
(Scala.js author here. TeaVM was brought to my attention yesterday.)

> What about Scala.js? Do they maintain their own version of Scala library? Is it possible to borrow this library to create TeaVM Scala port?

No, we don't. We use the normal Scala library. (with very few deviations, and mostly for performance)

We have implemented the necessary parts of "reflection" in our JDK implementation. There's not much, actually; it's mostly related to array types. `ClassLoader` is not needed. What you need is mostly `Class.getClass`, `Class.getComponentType` and `java.lang.reflect.Array`. Those need support from your emulation of the JVM object model, obviously, so you probably can't just take them from our implementations. But if it helps, feel free to do so, it's all BSD 3-clauses.

**Comment by konsoletyper** [comment]
TeaVM supports methods you said, like `Object.getClass`, etc. However, when I last tried to run Scala, TeaVM reported that several methods of `ClassLoader` were missing. I'll try again and write what methods exactly.

**Comment by sjrd** [comment]
That surprises me, [our `ClassLoader` implementation](https://github.com/scala-js/scala-js/blob/v0.6.4/javalanglib/src/main/scala/java/lang/ClassLoader.scala) is empty, and that does not prevent us from linking any program that is thrown at us. I never had a report saying that our linker was complaining about `ClassLoader`. Even this small stub is actually not really necessary; it's only used by sort-of-stub code in testing frameworks so that they can cross-compile on JVM and JS.

**Comment by konsoletyper** [comment]
Scala 2.11.7 with TeaVM built from master branch gives the following errors:

```
[INFO] JavaScript file built with errors
[ERROR] Class java.lang.InheritableThreadLocal was not found
    at scala.util.DynamicVariable$$anon$1.<init>(DynamicVariable.scala:41)
    at scala.util.DynamicVariable.<init>(DynamicVariable.scala:41)
    at scala.Console$.<init>(Console.scala:23)
    at scala.Console$.<clinit>
    at scala.Predef$.println(Predef.scala:310)
    at org.teavm.scalatest.Client$.main(Client.scala:5)
    at org.teavm.scalatest.Client.main
[ERROR] Class java.security.AccessControlException was not found
    at scala.sys.SystemProperties.wrapAccess
    at scala.sys.SystemProperties.contains(SystemProperties.scala:43)
    at scala.sys.SystemProperties.contains(SystemProperties.scala:31)
    at scala.sys.PropImpl.isSet(PropImpl.scala:18)
    at scala.sys.PropImpl.value(PropImpl.scala:17)
    at scala.sys.BooleanProp$BooleanPropImpl.value(BooleanProp.scala:36)
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31)
    at scala.util.control.NoStackTrace$.<clinit>
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22)
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94)
    at java.lang.Throwable.<init>(TThrowable.java:61)
    at java.lang.Exception.<init>(TException.java:26)
    at java.lang.CloneNotSupportedException.<init>(TCloneNotSupportedException.java:26)
    at java.lang.Object.clone(TObject.java:202)
[ERROR] Class java.security.AccessControlException was not found
    at scala.sys.SystemProperties.wrapAccess
    at scala.sys.SystemProperties.contains(SystemProperties.scala:43)
    at scala.sys.SystemProperties.contains(SystemProperties.scala:31)
    at scala.sys.PropImpl.isSet(PropImpl.scala:18)
    at scala.sys.PropImpl.value(PropImpl.scala:17)
    at scala.sys.BooleanProp$BooleanPropImpl.value(BooleanProp.scala:36)
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31)
    at scala.util.control.NoStackTrace$.<clinit>
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22)
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94)
    at java.lang.Throwable.<init>(TThrowable.java:61)
    at java.lang.Exception.<init>(TException.java:26)
    at java.lang.CloneNotSupportedException.<init>(TCloneNotSupportedException.java:26)
    at java.lang.Object.clone(TObject.java:202)
[ERROR] Field java.lang.System.in was not found
    at scala.Console$.<init>(Console.scala:26)
    at scala.Console$.<clinit>
    at scala.Predef$.println(Predef.scala:310)
    at org.teavm.scalatest.Client$.main(Client.scala:5)
    at org.teavm.scalatest.Client.main
[ERROR] Class java.lang.InheritableThreadLocal was not found
    at scala.util.DynamicVariable.value(DynamicVariable.scala:46)
    at scala.Console$.out(Console.scala:33)
    at scala.Console$.println(Console.scala:148)
    at scala.Predef$.println(Predef.scala:310)
    at org.teavm.scalatest.Client$.main(Client.scala:5)
    at org.teavm.scalatest.Client.main
```

So there is really no `ClassLoader` references. However, there is reference to `InheritableThreadLocal`. Well, TeaVM has implementation of `ThreadLocal`, but it's wrong since TeaVM now supports thread emulation. And I can't create ritght implementation since I'll need weak references, which are not supported in JavaScript, and there is no way to emulate them. I'll try to make substitutions and see what happens.

**Comment by sjrd** [comment]
> And I can't create ritght implementation since I'll need weak references, which are not supported in JavaScript, and there is no way to emulate them.

You don't exactly need weak references. You need a weak map. Good news, ES 6 has `WeakMap`, and it's implemented in modern browsers, now. So you can use that, and fallback to a leaking map if it's not available.

> `[ERROR] Field java.lang.System.in was not found`

Ah this is the one early thing for which we needed to adapt the Scala lib, indeed. We basically patched the initialization of [`scala.Console.in`](https://github.com/scala/scala/blob/v2.11.7/src/library/scala/Console.scala#L25) to be `new DynamicVariable[BufferedReader](null)` instead. I don't know whether it would be easy for TeaVM to patch up that. Alternatively, you could "implement" `java.lang.System.in` as an instance of `InputStream` whose `read()` method always returns `-1`, indicating EOF. Not sure what fits best in your philosophy. (for us the latter is a no-no because our philosophy is "everything that links should be correct").
