### ISSUE TITLE
NullPointerException in generateJumpStatement()

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#107]
I had this report from a CN1 user.  Unfortunately I don't have access to the source of the application that caused this.

~~~~
MyApplication: Unexpected error occured
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occured
	at org.teavm.maven.BuildJavascriptMojo.execute(BuildJavascriptMojo.java:261)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.teavm.javascript.StatementGenerator.generateJumpStatement(StatementGenerator.java:611)
	at org.teavm.javascript.Decompiler.closeExpiredBookmarks(Decompiler.java:496)
	at org.teavm.javascript.Decompiler.getRegularMethodStatement(Decompiler.java:373)
	at org.teavm.javascript.Decompiler.decompileAsyncCacheMiss(Decompiler.java:314)
	at org.teavm.javascript.Decompiler.decompileAsync(Decompiler.java:280)
	at org.teavm.javascript.Decompiler.decompile(Decompiler.java:217)
	at org.teavm.javascript.Decompiler.decompile(Decompiler.java:207)
	at org.teavm.vm.TeaVM.modelToAst(TeaVM.java:566)
	at org.teavm.vm.TeaVM.build(TeaVM.java:399)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:299)
	at org.teavm.maven.BuildJavascriptMojo.execute(BuildJavascriptMojo.java:256)
	... 21 more
~~~~

The version of TeaVM I'm running has the following around that part:

~~~~
Statement generateJumpStatement(BasicBlock target) {
        if (nextBlock == target && blockMap[target.getIndex()] == null) {
            return null;
        }
        Decompiler.Block block = blockMap[target.getIndex()];
        if (target.getIndex() == indexer.nodeAt(block.end)) {
            BreakStatement breakStmt = new BreakStatement();
            breakStmt.setLocation(currentLocation);
            breakStmt.setTarget(block.statement);
            return breakStmt;
        } else {
            ContinueStatement contStmt = new ContinueStatement();
            contStmt.setLocation(currentLocation);
            contStmt.setTarget(block.statement);
            return contStmt;
        }
    }
~~~~

where line 611 is 

~~~~
if (target.getIndex() == indexer.nodeAt(block.end)) {
~~~~

Most likely it is the "block" that is null (the `block.end` causes NullPointer). I'm not sure if this is something that can be fixed by just guarding against a null value or if block should never be null in this context and points to another problem...

**Comment by konsoletyper** [comment]
Sure, guarding is not enough. Try to convince user to share the code (or at least JAR file) in order to perform analysis. Without the code it's almost impossible to guess the reason.

**Comment by konsoletyper** [comment]
What I can do is to catch all exception at the level of method decompiler and rethrow it with more details, at least, what method caused the problem. Also, I realized that CN1 build server gets JAR files anyway. Can you fetch it from the server, or your police prohibits that?

**Comment by shannah** [comment]
I am looking into the feasibility of asking for access to the byte-code.   If the user consents I can probably obtain the maven project so you can test it directly.

**Comment by konsoletyper** [comment]
My last commit adds tracing of bytecode of method that caused failure. You can deploy TeaVM with this improvement on build server. I don't need entire maven project. JAR file is sufficient. Do users upload JAR files on your build server?

**Comment by konsoletyper** [comment]
Any progress with this issue?
