### ISSUE TITLE
Invalid Pointer Exception

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#118]
I'm getting an InvalidPointer exception on a project.  It seems that when restoring the method state after a thread context switch the `$ptr` variable is wrong.

This is the project:
https://github.com/shannah/invalid_pointer_issue

I am working against this branch of TeaVM because I needed to implement Timer.schedule(TimerTask, long, long) which wasn't implemented yet.
https://github.com/shannah/teavm/tree/timer_repeats

Relevant changes to Timer and TimerTask can be seen in this commit.
https://github.com/konsoletyper/teavm/commit/848417be0648476d910bddaaf6bfbd2e3913b64b

Originally the changes were much more minimal, but I fleshed it out to use more inefficient mechanisms (Window.setTimeout) to try to resolve this issue -- it was to no avail.

Some screenshots in the Chrome Debugger to show where the issue occurs.

![image](https://cloud.githubusercontent.com/assets/2677562/7658382/85a485f8-faee-11e4-81d5-a20c9c6d6e6a.png)

![image](https://cloud.githubusercontent.com/assets/2677562/7658383/9679157e-faee-11e4-81dd-0bba6f6137d9.png)

Note:  This project will have other problems because it uses things like Sockets which aren't implemented yet in the Javascript port, but this failure occurs before any of these things are used.  I suspect it is related to the use of Timer.schedule() but don't know for sure.

**Comment by shannah** [comment]
I just noticed that this project uses clearly synchronous APIs (reading from Storage) in a Class initializer.  It raises a warning during build - but I've basically been ignoring those types of warnings.

Could that cause something like this?  (the offending class is it.nice.hs3.ui.Navigator)

**Comment by shannah** [comment]
Oops... my mistake.  The offending class is it.nice.hs3.managers.PreferencesManager

**Comment by konsoletyper** [comment]
`teavm-flavour` shows the same error when opening modal windows, and I don't suppress any errors there. I'll try to find the error in Flavour, since its code base is much smaller and there are only few async methods. May be fixing error there will resolve your bug. Also, I should implement `<clinit>` splitting.

**Comment by konsoletyper** [comment]
Trying to build your project, I get the following error:

```
[ERROR] Method java.util.Timer.schedule(Ljava/util/TimerTask;JJ)V was not found
    at it.nice.hs3.ui.controls.ContainerElementsSwipe.updateContent(ContainerElementsSwipe.java:143)
    at it.nice.hs3.ui.controls.ContainerElementsSwipe$1.selectionChanged(ContainerElementsSwipe.java:104)
    at com.codename1.ui.util.EventDispatcher.fireSelectionEvent(EventDispatcher.java:377)
    at com.codename1.ui.list.DefaultListModel.setSelectedIndex(DefaultListModel.java:175)
    at com.codename1.ui.List.initComponentImpl(List.java:298)
    at com.codename1.ui.Container.initComponentImpl(Container.java:705)
    at com.codename1.ui.Container.insertComponentAt(Container.java:471)
    at com.codename1.ui.Container.addComponent(Container.java:431)
    at it.nice.hs3.HS3Application.showSplashScreen(HS3Application.java:144)
    at it.nice.hs3.HS3Application.start(HS3Application.java:71)
    at com.codename1.impl.html5.Stub.run(Stub.java:75)
    at com.codename1.ui.Display.callSerially(Display.java:764)
    at com.codename1.impl.html5.Stub.main(Stub.java:64)
[ERROR] Method java.util.Timer.schedule(Ljava/util/TimerTask;JJ)V was not found
    at com.codename1.system.DefaultCrashReporter.init(DefaultCrashReporter.java:136)
    at it.nice.hs3.HS3Application.init(HS3Application.java:39)
    at com.codename1.impl.html5.Stub.run(Stub.java:74)
    at com.codename1.ui.Display.callSerially(Display.java:764)
    at com.codename1.impl.html5.Stub.main(Stub.java:64)
```

**Comment by shannah** [comment]
TeaVM doesn't yet implement Timer.schedule(TimerTask,long,long) so I had to implement it.  There is a "dumb" implementation in 
https://github.com/shannah/teavm/tree/timer_repeats
That gets around this and brings me to the error in this issue.

**Comment by konsoletyper** [comment]
You can try with my latest commit.
