### ISSUE TITLE
Rare "Unexpected end of ZLIB input stream" exception when reusing VM

### ISSUE THREAD

**Issue by n3o59hf** [konsoletyper/teavm#147]
TeaVM 0.3.1
Java version "1.8.0_45"
x86_64 Linux

When using TeaVMTool multiple times from same VM (full recompilation), I'm rarely getting "Unexpected end of ZLIB input stream" exception.

It's quite hard to reproduce, but it seems to happen when one of compiled input jars changes.

Restarting VM helps with problem.

Here is log from my build:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':teavm:teavmc'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
        at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:48)
        at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:30)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:110)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:32)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:52)
        at org.teavm.resource.MapperClassHolderSource.get(MapperClassHolderSource.java:36)
        at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:46)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:39)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:27)
        at org.teavm.jso.plugin.NativeJavascriptClassRepository.examineIfJavaScriptClass(NativeJavascriptClassRepository.java:58)
        at org.teavm.jso.plugin.NativeJavascriptClassRepository.isJavaScriptClass(NativeJavascriptClassRepository.java:42)
        at org.teavm.jso.plugin.JavascriptNativeProcessor.processProgram(JavascriptNativeProcessor.java:327)
        at org.teavm.jso.plugin.JSObjectClassTransformer.transformClass(JSObjectClassTransformer.java:53)
        at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:69)
        at org.teavm.dependency.DependencyClassSource.access$000(DependencyClassSource.java:36)
        at org.teavm.dependency.DependencyClassSource$1.map(DependencyClassSource.java:43)
        at org.teavm.dependency.DependencyClassSource$1.map(DependencyClassSource.java:41)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:52)
        at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:54)
        at org.teavm.dependency.DependencyChecker.findMethodReader(DependencyChecker.java:303)
        at org.teavm.dependency.DependencyChecker.access$000(DependencyChecker.java:45)
        at org.teavm.dependency.DependencyChecker$1.map(DependencyChecker.java:76)
        at org.teavm.dependency.DependencyChecker$1.map(DependencyChecker.java:74)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:52)
        at org.teavm.dependency.DependencyChecker.linkMethod(DependencyChecker.java:266)
        at org.teavm.vm.TeaVM.entryPoint(TeaVM.java:247)
        at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:299)
        at com.edibleday.TeaVMTask.compTeaVM(TeaVMTask.kt:99)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at org.objectweb.asm.ClassReader.readClass(ClassReader.java:461)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
        at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:45)
        ... 92 more
```

Where 
`TeaVMTask.kt:99` : tool.generate()
and `org.gradle.` is build tool

**Comment by konsoletyper** [comment]
The only reason I can image is something is changing JAR files during TeaVM compilation process. I don't know anything about how Gradle works. Can it run several tasks in parallel? If so, I presume that `teavmc` task runs in parallel with Java compiler. I haven't experienced this ever with Maven, but Maven always starts a new JVM. I haven't experienced this with Eclipse, though Eclipse always runs in a single JVM, however it does not run project builders in parallel.

**Comment by n3o59hf** [comment]
I don't see parallel tasks happening in this case. Currently it seems that something (gradle, TeaVMTool or something between) is holding jar file in question open after compilation. Will continue to search for a cause.

**Comment by n3o59hf** [comment]
Maybe I found issue - classloader problem (classloader remembers previous file / caches class?). Here is minimal test that fails (with `java.io.IOException: Class not found`) when Jar from `URLClassLoader` is changed to another Jar.

`ab.jar` contains `ClassA` that on `getText()` constructs `ClassB` object and calls `getText()` on that
`ac.jar` does same with `ClassA` and `ClassC`
`com.company.Main` class executes `System.out.println(new ClassA().getText());`

This test doesn't use any build systems and jars included are taken from Maven. See `run.sh` for compilation and execution.

https://www.dropbox.com/s/ov6clptd6bc0e1v/TeaVMToolTest.tar.gz?dl=0

Any suggestions on how to workaround this issue? Would some kind of Classloader isolation work for TeaVM tool?

If file is deleted before rewriting then compilation goes through but `TeaVMTool` warns about `Class com.company.ClassB was not found`

**Comment by konsoletyper** [comment]
Thank you for your test. I encountered strange behaviour of URLClassLoader. When you run TeaVMTool the second time, you run it with the second classloader, which is completely independent from the first one. However, classLoader.getResource("com/company/ClassA.class") still returns valid URL. Opening this URL, I get IOException. That's not the behaviour I am expecting from a class loader. An obvious workaround is to make ClasspathResourceReader.hasResource to try to open resource and return `false` on the failed attempt. Nonetheless, I'll try to dig a little further, there might be something I miss.

> If file is deleted before rewriting then compilation goes through but TeaVMTool warns about Class com.company.ClassB was not found

TeaVM does report the similar warning gently, but only if it can get the appropriate information from URLClassLoader.

**Comment by konsoletyper** [comment]
This bug in fixed in upcoming 0.3.2 release

**Comment by konsoletyper** [comment]
@n3o59hf I pushed 0.3.2 artifacts to Maven Central. In a few hours you can update TeaVM version in your Gradle plugin.

**Comment by n3o59hf** [comment]
@konsoletyper Thank you!
I also found one other issue with my own code (the strange jar still opened after compilation one) - I didn't workaround one old JVM bug ( http://bugs.java.com/bugdatabase/view_bug.do?bug_id=5041014 ). From Java 7 URLClassLoaders now have `close()` method that workarounds this bug. Everything seems to work ok now.
