### ISSUE TITLE
[ERROR] Substitutor for bootstrap method java.lang.invoke.LambdaMetafactory.altMetafactory

### ISSUE THREAD

**Issue by Advanc3d** [konsoletyper/teavm#169]
Hi, i'm receiving the following exception while trying to compile test code with teavm maven plugin 0.4.1:

[ERROR] Substitutor for bootstrap method java.lang.invoke.LambdaMetafactory.altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; was not found
    at java.time.chrono.AbstractChronology.<clinit>
    at java.time.chrono.IsoChronology.<init>(IsoChronology.java:138)
    at java.time.chrono.IsoChronology.<clinit>(IsoChronology.java:128)
    at java.time.LocalDate.create(LocalDate.java:418)
    at java.time.LocalDate.of(LocalDate.java:269)
    at java.time.LocalDate.<clinit>(LocalDate.java:144)
    at java.time.LocalDateTime.ofEpochSecond(LocalDateTime.java:422)
    at sun.util.calendar.ZoneInfoFile.getZoneInfo(ZoneInfoFile.java:678)
    at sun.util.calendar.ZoneInfoFile.getZoneInfo(ZoneInfoFile.java:375)
    at sun.util.calendar.ZoneInfoFile.getZoneInfo0(ZoneInfoFile.java:139)
    at sun.util.calendar.ZoneInfoFile.getZoneInfo(ZoneInfoFile.java:115)
    at sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:589)
    at java.util.TimeZone.getTimeZone(TimeZone.java:560)
    at java.util.TimeZone.getTimeZone(TimeZone.java:516)
    at java.util.Formatter$FormatSpecifier.print(Formatter.java:4163)
    at java.util.Formatter$FormatSpecifier.print(Formatter.java:4060)
    at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2832)
    at java.util.Formatter$FormatSpecifier.print(Formatter.java:2740)
    at java.util.Formatter.format(Formatter.java:2508)
    at java.util.Formatter.format(Formatter.java:2455)
    at java.lang.String.format(String.java:2928)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:309)
...

also the same for LambdaMetafactory.metafactory

**Comment by konsoletyper** [comment]
You probably forgot to include `teavm-classlib` module to your project's dependencies, i.e.:
```xml
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>0.4.1</version>
      <scope>provided</scope>
    </dependency>
```

Also, I can see that you are using slf4j in your project. TeaVM is uncapable to transpile slf4j, as it uses reflection and string formatting. Fortunately, TeaVM comes with its own slf4j provider, which you should include into your project's dependencies:

```xml
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-extras-slf4j</artifactId>
      <version>0.4.1</version>
      <scope>provided</scope>
    </dependency>
```

**Comment by Advanc3d** [comment]
Ok thanks. I thought *teavm-classlib* should be used by maven plugin automatically.
