### ISSUE TITLE
Problem with Eclipse and TeaVM setup

### ISSUE THREAD

**Issue by hoonto** [konsoletyper/teavm#174]
Hi,
I am new to both teavm and maven and haven't used Eclipse in quite a long time so this is probably a user error, but after following the instructions on https://github.com/konsoletyper/teavm/wiki/Eclipse-tutorial
I am having this problem during the step of "Creating a project". 

I have installed maven (via the Eclipse Marketplace - Maven Integration for Eclipse (Luna) 1.5.0). Perhaps this is where my problem is. I have also installed teavm (using the instructions).

Selecting teavm archetype:

![eclipse-teavm-problem5](https://cloud.githubusercontent.com/assets/3254018/12122654/5cf34d9a-b3aa-11e5-9f20-70c998c4ec1d.png)

Where I am entering information for my new maven (teavm?) project:

![eclipse-teavm-problem3](https://cloud.githubusercontent.com/assets/3254018/12120361/9d86cf1e-b39e-11e5-9c62-3b5d6068ffa3.png)

The errors I get:

![eclipse-teavm-problem4](https://cloud.githubusercontent.com/assets/3254018/12120432/f070dea4-b39e-11e5-830f-11694c90bc3e.png)

**Comment by hoonto** [comment]
So I uninstalled eclipse and reinstalled, reinstalled maven, reinstalled teavm eclipse plugin, and now when I create a project following those instructions I'm getting a FrameworkEvent ERROR:

org.osgi.framework.BundleException: Could not resolve module: teavm-eclipse-plugin [319]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

![eclipse-teavm-problem6](https://cloud.githubusercontent.com/assets/3254018/12122781/33cd0914-b3ab-11e5-92c4-b6a6053bae6e.png)

**Comment by hoonto** [comment]
And using the command line instructions I'm getting a build failure when I run `mvn clean package`:

```sh
mmullens@mlm ~/dev/teavm-test $ mvn -DarchetypeCatalog=local \
  -DarchetypeGroupId=org.teavm \
  -DarchetypeArtifactId=teavm-maven-webapp \
  -DarchetypeVersion=0.4.3 archetype:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.teavm:teavm-maven-webapp:0.4.3 -> ] found in catalog local
Define value for property 'groupId': : com.hoonto
Define value for property 'artifactId': : test
Define value for property 'version':  1.0-SNAPSHOT: : 
Define value for property 'package':  com.hoonto: : 
Confirm properties configuration:
groupId: com.hoonto
artifactId: test
version: 1.0-SNAPSHOT
package: com.hoonto
 Y: : 
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: teavm-maven-webapp:0.4.3
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.hoonto
[INFO] Parameter: artifactId, Value: test
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: com.hoonto
[INFO] Parameter: packageInPathFormat, Value: com/hoonto
[INFO] Parameter: package, Value: com.hoonto
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: com.hoonto
[INFO] Parameter: artifactId, Value: test
[INFO] project created from Archetype in dir: /home/mmullens/dev/teavm-test/test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.665 s
[INFO] Finished at: 2016-01-05T13:13:47-05:00
[INFO] Final Memory: 25M/964M
[INFO] ------------------------------------------------------------------------
mmullens@mlm ~/dev/teavm-test $ cd test
mmullens@mlm ~/dev/teavm-test/test $ mvn clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.teavm:teavm-maven-plugin:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.069 s
[INFO] Finished at: 2016-01-05T13:13:53-05:00
[INFO] Final Memory: 16M/964M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.teavm:teavm-maven-plugin:1.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.teavm:teavm-maven-plugin:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by konsoletyper** [comment]
Sorry, it seems that teavm archetype is broken. After creating a project you should open `pom.xml` file and find the following line:

```xml
<teavm.version>${project.version}</teavm.version>
```

Replace **${project.version}** with **0.4.3** and try to rebuild the project.

**Comment by hoonto** [comment]
Thanks @konsoletyper , that definitely got me further, and I also changed the jvm version from 1.8 to 1.7 in the pom.xml (as I'm running 1.7 here). However now I'm getting another error about injecting org.teavm.maven.BuildJavascriptMojo
(java.lang.TypeNotPresentException):

```sh
mmullens@mlm ~/dev/test $ mvn clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ test ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/mmullens/dev/test/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/mmullens/dev/test/target/classes
[INFO] 
[INFO] --- teavm-maven-plugin:0.4.3:compile (web-client) @ test ---
[WARNING] Error injecting: org.teavm.maven.BuildJavascriptMojo
java.lang.TypeNotPresentException: Type org.teavm.maven.BuildJavascriptMojo not present
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:147)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.UnsupportedClassVersionError: org/teavm/maven/BuildJavascriptMojo : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:139)
	... 42 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.008 s
[INFO] Finished at: 2016-01-07T04:23:09-05:00
[INFO] Final Memory: 30M/964M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.4.3:compile (web-client) on project test: Execution web-client of goal org.teavm:teavm-maven-plugin:0.4.3:compile failed: Unable to load the mojo 'compile' in the plugin 'org.teavm:teavm-maven-plugin:0.4.3' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/teavm/maven/BuildJavascriptMojo : Unsupported major.minor version 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.teavm:teavm-maven-plugin:0.4.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/mmullens/.m2/repository/org/teavm/teavm-maven-plugin/0.4.3/teavm-maven-plugin-0.4.3.jar
[ERROR] urls[1] = file:/home/mmullens/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[2] = file:/home/mmullens/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[3] = file:/home/mmullens/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[4] = file:/home/mmullens/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[5] = file:/home/mmullens/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/home/mmullens/.m2/repository/org/teavm/teavm-tooling/0.4.3/teavm-tooling-0.4.3.jar
[ERROR] urls[7] = file:/home/mmullens/.m2/repository/org/teavm/teavm-core/0.4.3/teavm-core-0.4.3.jar
[ERROR] urls[8] = file:/home/mmullens/.m2/repository/org/ow2/asm/asm-debug-all/5.0.4/asm-debug-all-5.0.4.jar
[ERROR] urls[9] = file:/home/mmullens/.m2/repository/com/carrotsearch/hppc/0.6.1/hppc-0.6.1.jar
[ERROR] urls[10] = file:/home/mmullens/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[11] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-java/2.47.2/selenium-java-2.47.2.jar
[ERROR] urls[12] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.47.2/selenium-chrome-driver-2.47.2.jar
[ERROR] urls[13] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.47.2/selenium-htmlunit-driver-2.47.2.jar
[ERROR] urls[14] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.47.2/selenium-firefox-driver-2.47.2.jar
[ERROR] urls[15] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.47.2/selenium-ie-driver-2.47.2.jar
[ERROR] urls[16] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.47.2/selenium-safari-driver-2.47.2.jar
[ERROR] urls[17] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-support/2.47.2/selenium-support-2.47.2.jar
[ERROR] urls[18] = file:/home/mmullens/.m2/repository/org/webbitserver/webbit/0.4.14/webbit-0.4.14.jar
[ERROR] urls[19] = file:/home/mmullens/.m2/repository/io/netty/netty/3.5.2.Final/netty-3.5.2.Final.jar
[ERROR] urls[20] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-leg-rc/2.47.2/selenium-leg-rc-2.47.2.jar
[ERROR] urls[21] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.47.2/selenium-remote-driver-2.47.2.jar
[ERROR] urls[22] = file:/home/mmullens/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar
[ERROR] urls[23] = file:/home/mmullens/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
[ERROR] urls[24] = file:/home/mmullens/.m2/repository/org/seleniumhq/selenium/selenium-api/2.47.2/selenium-api-2.47.2.jar
[ERROR] urls[25] = file:/home/mmullens/.m2/repository/org/apache/httpcomponents/httpclient/4.4.1/httpclient-4.4.1.jar
[ERROR] urls[26] = file:/home/mmullens/.m2/repository/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.jar
[ERROR] urls[27] = file:/home/mmullens/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[28] = file:/home/mmullens/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[29] = file:/home/mmullens/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar
[ERROR] urls[30] = file:/home/mmullens/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar
[ERROR] urls[31] = file:/home/mmullens/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.2/jackson-databind-2.6.2.jar
[ERROR] urls[32] = file:/home/mmullens/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.2/jackson-annotations-2.6.2.jar
[ERROR] urls[33] = file:/home/mmullens/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.2/jackson-core-2.6.2.jar
[ERROR] urls[34] = file:/home/mmullens/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.18/htmlunit-2.18.jar
[ERROR] urls[35] = file:/home/mmullens/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar
[ERROR] urls[36] = file:/home/mmullens/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar
[ERROR] urls[37] = file:/home/mmullens/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
[ERROR] urls[38] = file:/home/mmullens/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[39] = file:/home/mmullens/.m2/repository/org/apache/httpcomponents/httpmime/4.5/httpmime-4.5.jar
[ERROR] urls[40] = file:/home/mmullens/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[ERROR] urls[41] = file:/home/mmullens/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.17/htmlunit-core-js-2.17.jar
[ERROR] urls[42] = file:/home/mmullens/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar
[ERROR] urls[43] = file:/home/mmullens/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
[ERROR] urls[44] = file:/home/mmullens/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.22/nekohtml-1.9.22.jar
[ERROR] urls[45] = file:/home/mmullens/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.16/cssparser-0.9.16.jar
[ERROR] urls[46] = file:/home/mmullens/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar
[ERROR] urls[47] = file:/home/mmullens/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[48] = file:/home/mmullens/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.2.12.v20150709/websocket-client-9.2.12.v20150709.jar
[ERROR] urls[49] = file:/home/mmullens/.m2/repository/org/eclipse/jetty/jetty-util/9.2.12.v20150709/jetty-util-9.2.12.v20150709.jar
[ERROR] urls[50] = file:/home/mmullens/.m2/repository/org/eclipse/jetty/jetty-io/9.2.12.v20150709/jetty-io-9.2.12.v20150709.jar
[ERROR] urls[51] = file:/home/mmullens/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.2.12.v20150709/websocket-common-9.2.12.v20150709.jar
[ERROR] urls[52] = file:/home/mmullens/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.2.12.v20150709/websocket-api-9.2.12.v20150709.jar
[ERROR] urls[53] = file:/home/mmullens/.m2/repository/junit/junit/4.11/junit-4.11.jar
[ERROR] urls[54] = file:/home/mmullens/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by konsoletyper** [comment]
TeaVM requires Java 8, so you have to install JDK 8 first. I guess this is the reason. Please, look at the cause of the exception. It tells that your JVM does not support class file version.

**Comment by hoonto** [comment]
Yes, that was the issue, thank you. It all works very well now with the modification to pom.xml that you had mentioned.
