### ISSUE TITLE
TeaVM plugin throwing exception in IntelliJ 2016.2.1

### ISSUE THREAD

**Issue by liraz** [konsoletyper/teavm#205]
What am i missing? any clue?
Happens when setting the teavm plugin to compile resources on update.

Here's the exception:
`Error:TeaVM: Error: class org.teavm.vm.TeaVMPluginLoader$PluginDescriptorFiller has interface org.objectweb.asm.ClassVisitor as super class
java.lang.IncompatibleClassChangeError: class org.teavm.vm.TeaVMPluginLoader$PluginDescriptorFiller has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.teavm.vm.TeaVMPluginLoader.readDescriptor(TeaVMPluginLoader.java:124)
	at org.teavm.vm.TeaVMPluginLoader.orderPlugins(TeaVMPluginLoader.java:82)
	at org.teavm.vm.TeaVMPluginLoader.load(TeaVMPluginLoader.java:72)
	at org.teavm.vm.TeaVM.installPlugins(TeaVM.java:829)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:306)
	at org.teavm.idea.jps.TeaVMBuild.perform(TeaVMBuild.java:131)
	at org.teavm.idea.jps.TeaVMBuilder.build(TeaVMBuilder.java:68)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1237)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:911)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:983)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:696)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:194)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by konsoletyper** [comment]
Seems like you don't build TeaVM plugin properly. Sorry, there's no official release, nor documentation. I'll publish plugin somewhere when I release the next version of TeaVM. TeaVM uses asm5, which clashes with IDEA and JPS, so plugin uses specially built uberjar version of TeaVM with ASM included and shaded. You have to build this jar manually, see `https://github.com/konsoletyper/teavm/blob/master/tools/idea/jps-plugin/pom.xml`

**Comment by liraz** [comment]
Thanks konsoletyper, when is this version released?
I just checked compiling a bulk of 12,000 classes with different names all of them are used and initialized also assigned to their properties some values, and it took 2:30 minutes to build the whole thing - it's amazing!!
I really want to incorporate this framework into my projects..

**Comment by konsoletyper** [comment]
Do you really need releases? You better sit on the bleeding edge, and if you feel your project becomes stable enought, then you can ask and I'll try to stabilize and release TeaVM.
