### ISSUE TITLE
Maven problem with 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#211]
Replaced the 0.4.3 with the new 1.0.0-SNAPSHOT, Now our application does not build anymore. Here is the problem part. Whatever it is it doesnt do this with 0.4.3.

From Eclipse:

```
Errors occurred during the build.
Errors running builder 'TeaVM builder' on project 'x'.
org.teavm.model.util.InstructionVariableMapper
```

From command line:
```

	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:246)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:217)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:127)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
```

**Comment by konsoletyper** [comment]
I can't find anything useful to reproduce the problem? Can you give me the full build log? Can you give at least your `pom.xml` file?

**Comment by bertung** [comment]
Here is the pom.xml. I only changes the version number of teavm

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>NeuroKernelTeaVM</groupId>
  <artifactId>neurokernel</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>war</packaging>

  <properties>
    <java.version>1.8</java.version>
    <teavm.version>${project.version}</teavm.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!-- Emulator of Java class library for TeaVM -->
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- JavaScriptObjects (JSO) - a JavaScript binding for TeaVM -->
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso-apis</artifactId>
      <version>${teavm.version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- Servlet 3.1 specification -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
   <dependency>
    	<groupId>com.neurokernel</groupId>
    	<artifactId>neurokernel_core</artifactId>
    	<version>1.0.0</version>
    	<scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- Configure Java compiler to use Java 8 syntax  -->
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>

      <!-- Configure WAR plugin to include JavaScript files generated by TeaVM -->
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.4</version>
        <configuration>
          <webResources>
            <resource>
              <directory>${project.build.directory}/generated/js</directory>
            </resource>
          </webResources>
        </configuration>
      </plugin>

      <!-- Configure TeaVM -->
      <plugin>
        <groupId>org.teavm</groupId>
        <artifactId>teavm-maven-plugin</artifactId>
        <version>${teavm.version}</version>
        <executions>
          <execution>
            <id>web-client</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <!-- Directory where TeaVM should put generated files. This configuration conforms to the settings
                   of the WAR plugin -->
              <targetDirectory>${project.build.directory}/generated/js/neurokernel</targetDirectory>
			  <targetFileName>myapp.js</targetFileName>
              <!-- Main class, containing static void main(String[]) -->
              <mainClass>com.neurokernel.client.system.Client</mainClass>
		      <minifying>false</minifying>
              <!-- Whether TeaVM should produce minified JavaScript. Can reduce JavaScript file size more than
                   two times -->
              <runtime>MERGED</runtime>

		      <mainPageIncluded>false</mainPageIncluded>
	 
              <!-- Whether TeaVM should produce debug information for its built-in debugger -->
              <debugInformationGenerated>false</debugInformationGenerated>

              <!-- Whether TeaVM should produce source maps file -->
              <sourceMapsGenerated>false</sourceMapsGenerated>

              <!-- Whether TeaVM should also put source files into output directory,
                   for compatibility with source maps -->
              <sourceFilesCopied>false</sourceFilesCopied>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by konsoletyper** [comment]
I still can't understand the reason. Did you read http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException ?
I claims that you might have typed wrong command line. There's nothing about TeaVM in the build log you specified. What about TeaVM 1.0.0-SNAPSHOT? Where did you get it? Did you clone TeaVM repository and run `mvn clean install`?

**Comment by bertung** [comment]
Yep that was a clean install from the clone of your latest repository. 1.0.0-SNAPSHOT is defined by you everywhere in your project files including pom.xml files. I actually use the eclipse, and org.teavm.model.util.InstructionVariableMapper may have a problem.

**Comment by konsoletyper** [comment]
Did you update Eclipse plugin as well? This still does not help to reproduce the issue.

**Comment by bertung** [comment]
Wouldn't it be easier to put the latest binaries periodically to a repository so that we can grab it from there? The command line was complaining about the "clean". The "mvn install" went trough; however, this time only the runtime code is produced, rest is missing. Is it possible that you use some other environment(another computer may be) other than your development machine to reproduce this?

**Comment by bertung** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/9346984/17770242/43dabb98-6545-11e6-93c7-1d32586744c3.jpg)

**Comment by bertung** [comment]
Wait you are right teavm-maven-plugin is the older one. Why it is not produced with the latest?

**Comment by bertung** [comment]
The pom is getting the latest teavm maven plugin.

**Comment by bertung** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/9346984/17770533/00bf57c2-6547-11e6-8025-632e5bc576a1.jpg)

**Comment by bertung** [comment]
I am bailing on this. I will wait your 1.0.0 update to the public repository.

**Comment by konsoletyper** [comment]
You'll wait too much. You better realize what you are doing wrong. There's nothing about TeaVM in build logs you specified, so I can't reproduce the problem.

**Comment by bertung** [comment]
You bet
