### ISSUE TITLE
java.lang.AssertionError during LoopInversion method optimization

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#225]
When enabling full or advanced optimization in TeaVM 1.0.0, i am getting the following assertion error:

`
[INFO] Building JavaScript file
Exception in thread "main" java.lang.AssertionError
    at org.teavm.model.util.PhiUpdater.use(PhiUpdater.java:401)
    at org.teavm.model.util.PhiUpdater.renameVariables(PhiUpdater.java:226)
    at org.teavm.model.util.PhiUpdater.updatePhis(PhiUpdater.java:140)
    at org.teavm.model.optimization.LoopInversionImpl.apply(LoopInversionImpl.java:117)
    at org.teavm.model.optimization.LoopInversion.optimize(LoopInversion.java:24)
    at org.teavm.vm.TeaVM.processMethod(TeaVM.java:481)
    at org.teavm.vm.TeaVM.optimize(TeaVM.java:458)
    at org.teavm.vm.TeaVM.build(TeaVM.java:375)
    at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:416)
    at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:105)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
`
I don't know what is causing this issue, as there is no further output.

**Comment by mirkosertic** [comment]
After some debugging, i got the following code snipped that seems to cause the assertion:

``
	protected LuaValue arithmt(LuaValue tag, LuaValue op2) {
		LuaValue h = this.metatag(tag);
		if ( h.isnil() ) {
			h = op2.metatag(tag);
			if ( h.isnil() )
				error( "attempt to perform arithmetic "+tag+" on "+typename()+" and "+op2.typename() );
		}
		return h.call( this, op2 );
	}
``

**Comment by konsoletyper** [comment]
Ok, I'll try to look at this, but there are little chances to find the reason. Instead, I can improve optimizer to print IR if something went wrong. This should give me more information. Also, a single method does not provide enough information, since TeaVM performs link-time optimizations, so one method can be affected by any other method, it's hard to predict. The best way to debug the problem is to get code that causes compiler failure and try to compile it. Thus you should provide me with the instructions where to get and how to compile your code.

**Comment by mirkosertic** [comment]
ok, i will provide some sample code :-) Thanks for your support.

**Comment by konsoletyper** [comment]
Can you pull latest master and build your project again? I added some code that dumps IR when error occurs, so I'll get enough information to trace the bug.

**Comment by mirkosertic** [comment]
Now i am getting the following output:

``
[INFO] Building JavaScript file
Exception in thread "main" java.lang.AssertionError: Variable used before definition: 5
	at org.teavm.model.util.PhiUpdater.use(PhiUpdater.java:397)
	at org.teavm.model.util.PhiUpdater.renameVariables(PhiUpdater.java:226)
	at org.teavm.model.util.PhiUpdater.updatePhis(PhiUpdater.java:140)
	at org.teavm.model.optimization.LoopInversionImpl.apply(LoopInversionImpl.java:117)
	at org.teavm.model.optimization.LoopInversion.optimize(LoopInversion.java:24)
	at org.teavm.vm.TeaVM.processMethod(TeaVM.java:483)
	at org.teavm.vm.TeaVM.optimize(TeaVM.java:459)
	at org.teavm.vm.TeaVM.build(TeaVM.java:376)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:427)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:110)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
``

**Comment by konsoletyper** [comment]
Is that's all you got? You should have seen method's IR somewhere in stderr.

**Comment by mirkosertic** [comment]
That was all, even with Maven debug enabled

**Comment by konsoletyper** [comment]
Looks strange. I tried to cause an error in optimization passes artificially and got error message like this

```
[INFO] Building JavaScript file
Error optimizing program for methodorg.teavm.samples.benchmark.shared.Scene.calculate()V:
var @0 as this
var @1
var @2
var @3 as currentTime
...
```

How do you run Maven? What OS are you using?

**Comment by konsoletyper** [comment]
So, what's the status? Could you get IR listing I need? If you can't get it, why don't you provide me with instructions how to build your project to reproduce the issue?

**Comment by mirkosertic** [comment]
Sorry for the late response. Well, i cannot see any further compiler output here. I am using a Windows 10 machine with Maven 3.2.5 here, but i also checked on my Fedora 24 box with Maven 3.3, and see the same results.

You can see for yourself, just get the latest GameComposer sources, and replace the teavm.version Properties in the following maven modules to 1.0.0-SNAPSHOT:

- gameengine-editor/pom.xml
- gameengine-teavmrenderer/pom.xml

and trigger a mvn clean install on the root pom.xml. You probably have to enable optimization for the teavm compiler, as it is disabled due to this bug.

The build needs a node.js environment with some packages installed, and an Android SDK as well. Just check the .travis.yml file for a hint.

**Comment by konsoletyper** [comment]
Looks like f61cfb23b52f5cfa55954e6322c11ec835d87411 has fixed the issue. Please, check it.

**Comment by mirkosertic** [comment]
I can confirm, there are no further compiler errors with that revision-
