### ISSUE TITLE
JSO support on JVM in order to debug in tests

### ISSUE THREAD

**Issue by liraz** [konsoletyper/teavm#233]
The following test fails on exception:
```java
@RunWith(TeaVMTestRunner.class)
public class HtmlElementTest {
    @Test
    public void generalHtmlElementTest() {
        HTMLDocument document = Window.current().getDocument();
        HTMLElement div = document.createElement("div");
        div.setInnerHTML("Text");
        assertEquals("Text", div.getInnerHTML());
    }
}
```

Exception:
```
java.lang.UnsatisfiedLinkError: org.teavm.jso.browser.Window.current()Lorg/teavm/jso/browser/Window;
	at org.teavm.jso.browser.Window.current(Native Method)
	at org.teavm.tests.HtmlElementTest.generalHtmlElementTest(HtmlElementTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.teavm.junit.TeaVMTestRunner.runInJvm(TeaVMTestRunner.java:238)
	at org.teavm.junit.TeaVMTestRunner.runChild(TeaVMTestRunner.java:199)
	at org.teavm.junit.TeaVMTestRunner.run(TeaVMTestRunner.java:146)
```

Adding the "@SkipJVM" will make it pass.
But now i can't debug, since i am not running on JVM.

How complicated is it for JSO annotations to fully work on the JVM with htmlunit?
Thanks

**Comment by konsoletyper** [comment]
If the only reason why you want JSO in JVM is debugging, then why don't you learn how to debug TeaVM apps?

**Comment by liraz** [comment]
From what i researched so far, the possibilities for debug are source maps & the IDE plugins that integrate with the chrome plugin, that provide better debug information than the lacking source maps.
But what if i am running the test with htmlunit? how can i do a debug there?
I want to be able to debug my htmlunit test... not teavm applications.
GWT guys did back then with the hosted mode, that emulated the whole browser on the JVM - this is how you could debug your tests.
But now with JSInterop and super dev mode, not really possible anymore.

**Comment by konsoletyper** [comment]
I don't know. I don't have time to implement JSO in JVM

**Comment by liraz** [comment]
Seems too complex.
