### ISSUE TITLE
WASM: NPE while compiling Long.parseLong(String)

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#260]
The following code doesn't compile to WASM and leads to a NPE:

```
package de.mirkosertic;

public class Main {

    public static void main(String[] args) {
        Long theLong = Long.parseLong("12345");
    }
}
```

The following stacktrace is generated by Maven:

```
Caused by: java.lang.NullPointerException
	at org.teavm.platform.plugin.ResourceAccessorTransformer.transformClass(ResourceAccessorTransformer.java:43)
	at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:67)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:47)
	at org.teavm.dependency.DependencyChecker.createClassDependency(DependencyChecker.java:306)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:45)
	at org.teavm.dependency.DependencyChecker.linkClass(DependencyChecker.java:269)
	at org.teavm.dependency.DependencyGraphBuilder$1.invokeSpecial(DependencyGraphBuilder.java:616)
	at org.teavm.dependency.DependencyGraphBuilder$1.invoke(DependencyGraphBuilder.java:596)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:182)
	at org.teavm.model.instructions.InvokeInstruction.acceptVisitor(InvokeInstruction.java:69)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:280)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:128)
	at org.teavm.dependency.DependencyChecker.lambda$scheduleMethodAnalysis$10(DependencyChecker.java:399)
	at org.teavm.dependency.DependencyChecker.processQueue(DependencyChecker.java:512)
	at org.teavm.dependency.DependencyChecker.processDependencies(DependencyChecker.java:525)
	at org.teavm.vm.TeaVM.build(TeaVM.java:347)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:428)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:110)
```

**Comment by konsoletyper** [comment]
Basically, that's not bug, it's a missing feature. WebAssembly backend does not support resources, which are internal mechanism to embed some metadata like locales, date and numer formats and Unicode tables. Your particular example uses `Long.parseLong`, which in turn uses `Character.getNumericValue`, which tries to access unicode metadata.

**Comment by konsoletyper** [comment]
Fixed
