### ISSUE TITLE
WASM: OOM while trying to compile Java 7 switch(string) statement

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#261]
Trying to compile the following code to WASM results in OOM:

```
package de.mirkosertic;

public abstract class Main {

    public static final Main ONE = new Main() {};
    public static final Main TWO = new Main() {};
    public static final Main THREE = new Main() {};

    public static Main valueOf(String aValue) {
        switch (aValue) {
            case "ONE":
                return ONE;
            case "TWO":
                return TWO;
            case "THREE":
                return THREE;
        }
        throw new IllegalArgumentException();
    }

    public static void main(String[] args) {
        Main theInstance = valueOf("");
    }
}
```

**Comment by konsoletyper** [comment]
Sounds strange. There isn't such thing in bytecode like "string switch statement". It's compiler feature, not bytecode feature. Did you try int switch? What about String.equals/String.hashCode?

**Comment by mirkosertic** [comment]
IntelliJ decompiler shows something like this:

```
package de.mirkosertic;

public abstract class Main {
    public static final Main ONE = new Main() {
    };
    public static final Main TWO = new Main() {
    };
    public static final Main THREE = new Main() {
    };

    public Main() {
    }

    public static Main valueOf(String aValue) {
        byte var2 = -1;
        switch(aValue.hashCode()) {
        case 78406:
            if(aValue.equals("ONE")) {
                var2 = 0;
            }
            break;
        case 83500:
            if(aValue.equals("TWO")) {
                var2 = 1;
            }
            break;
        case 79801726:
            if(aValue.equals("THREE")) {
                var2 = 2;
            }
        }

        switch(var2) {
        case 0:
            return ONE;
        case 1:
            return TWO;
        case 2:
            return THREE;
        default:
            throw new IllegalArgumentException();
        }
    }

    public static void main(String[] args) {
        Main theInstance = valueOf("");
    }
}
```

The following stacktrace is finally generted by WASM compiler:

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:113)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:207)
	at org.teavm.backend.wasm.model.expression.WasmSwitch.acceptVisitor(WasmSwitch.java:56)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:122)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.line(WasmRenderingVisitor.java:130)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.renderBlock(WasmRenderingVisitor.java:177)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:164)
	at org.teavm.backend.wasm.model.expression.WasmBlock.acceptVisitor(WasmBlock.java:53)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:122)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.line(WasmRenderingVisitor.java:130)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.renderBlock(WasmRenderingVisitor.java:177)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:164)
	at org.teavm.backend.wasm.model.expression.WasmBlock.acceptVisitor(WasmBlock.java:53)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:122)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.line(WasmRenderingVisitor.java:130)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.renderBlock(WasmRenderingVisitor.java:177)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:164)
	at org.teavm.backend.wasm.model.expression.WasmBlock.acceptVisitor(WasmBlock.java:53)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:122)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.line(WasmRenderingVisitor.java:130)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.renderBlock(WasmRenderingVisitor.java:177)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:164)
	at org.teavm.backend.wasm.model.expression.WasmBlock.acceptVisitor(WasmBlock.java:53)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.append(WasmRenderingVisitor.java:122)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.line(WasmRenderingVisitor.java:130)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.renderBlock(WasmRenderingVisitor.java:177)
	at org.teavm.backend.wasm.render.WasmRenderingVisitor.visit(WasmRenderingVisitor.java:164)
	at org.teavm.backend.wasm.model.expression.WasmBlock.acceptVisitor(WasmBlock.java:53)
```

Under the hood equals seems to be used for comparison, at least at bytecode level. The problem is

**Comment by mirkosertic** [comment]
Surprisingly this seems to work:

```
package de.mirkosertic;

public abstract class Main {

    public static final Main ONE = new Main() {};
    public static final Main TWO = new Main() {};
    public static final Main THREE = new Main() {};

    public static Main valueOf(String aValue) {
        switch (aValue) {
            case "ONE":
                return ONE;
            case "TWO":
                return TWO;
            case "THRE":
                return THREE;
        }
        throw new IllegalArgumentException();
    }

    public static void main(String[] args) {
        Main theInstance = valueOf("");
    }
}
```

case "THREE": OOM during compilation
case "THRE": works

**Comment by konsoletyper** [comment]
I found the reason. WebAssembly supports only alternative to JVM's `tableswitch`, `br_table`, but does not support anything like `lookupswitch`. TeaVM implements quick and dirty approach to convert `lookupswitch` to `br_table` by growing switch table. If string hashes differ by large amount (millions), we end up with huge switch table. I think after hitting some threshold TeaVM should not generate `br_table` and fallback to sequence of `br_if` instead.
