### ISSUE TITLE
Compiler error if FULL optimization is enabled

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#271]
Enabling FULL optimization for the JS compiler leads to the following error:

```
[INFO] Building JavaScript file
Error optimizing program for method org.luaj.vm2.LuaString.neg()Lorg/luaj/vm2/LuaValue;:
var @this as this
var @d as d
$0
    goto $1
$1
  at 'org/luaj/vm2/LuaString.java' 226
    nop
    @d := invoke `org.luaj.vm2.LuaString.scannumber()D` @this
    nop
    @8 := invokeStatic `org.teavm.jso.impl.JS.wrap(D)Lorg/teavm/jso/JSObject;` @d
    @7 := invokeStatic `java.lang.Double.isNaN$js_body$_43(Lorg/teavm/jso/JSObject;)Lorg/teavm/jso/JSObject;` @8
    @9 := invokeStatic `org.teavm.jso.impl.JS.unwrapBoolean(Lorg/teavm/jso/JSObject;)Z` @7
    @2 := @9
    if @2 == 0 then goto $2 else goto $3
$2
  at 'org/luaj/vm2/LuaString.java' 226
    @3 := - @d
  at unknown location
    initClass org.luaj.vm2.LuaValue
  at 'org/luaj/vm2/LuaValue.java' 3166
    nop
  at unknown location
    initClass org.luaj.vm2.LuaDouble
  at 'org/luaj/vm2/LuaDouble.java' 78
    nop
    @164 := cast @3 from DOUBLE to INT
  at 'org/luaj/vm2/LuaDouble.java' 79
    nop
    @165 := cast @164 from INT to DOUBLE
    @166 := @3 compareTo @165
    if @166 != 0 then goto $36 else goto $37
$3
  at 'org/luaj/vm2/LuaValue.java' 2000
    nop
    @10 := field org.luaj.vm2.LuaValue.UNM as `Lorg/luaj/vm2/LuaString;`
    @11 := 'attempt to perform arithmetic on '
  at 'org/luaj/vm2/LuaValue.java' 3355
    nop
  at 'org/luaj/vm2/LuaValue.java' 3340
    nop
  at 'org/luaj/vm2/LuaString.java' 200
    nop
    @181 := field org.luaj.vm2.LuaString.s_metatable as `Lorg/luaj/vm2/LuaValue;`
  at unknown location
    @160 := @181
  at 'org/luaj/vm2/LuaValue.java' 3341
    nop
    if @160 !== null then goto $34 else goto $35
$4
    @6 := phi @4 from $38, @5 from $5
  at 'org/luaj/vm2/LuaString.java' 226
    return @6
$5
    @28 := phi @42 from $6, @43 from $7, @44 from $8, @47 from $9
  at 'org/luaj/vm2/LuaValue.java' 1724
    nop
  at 'org/luaj/vm2/LuaValue.java' 1986
    nop
    @34 := field org.luaj.vm2.LuaValue.CALL as `Lorg/luaj/vm2/LuaString;`
    @35 := 'attempt to call '
    @36 := invoke `org.luaj.vm2.LuaValue.checkmetatag(Lorg/luaj/vm2/LuaValue;Ljava/lang/String;)Lorg/luaj/vm2/LuaValue;` @20, @34, @35
  at unknown location
    @30 := @36
  at 'org/luaj/vm2/LuaValue.java' 1748
    nop
    @32 := invokeStatic `org.luaj.vm2.LuaValue.varargsOf(Lorg/luaj/vm2/LuaValue;Lorg/luaj/vm2/Varargs;)Lorg/luaj/vm2/Varargs;` @20, @28
    @33 := invoke `org.luaj.vm2.LuaValue.invoke(Lorg/luaj/vm2/Varargs;)Lorg/luaj/vm2/Varargs;` @30, @32
  at unknown location
    @31 := @33
    @29 := @31
    @26 := @29
  at 'org/luaj/vm2/LuaValue.java' 1519
    @27 := invokeVirtual `org.luaj.vm2.Varargs.arg1()Lorg/luaj/vm2/LuaValue;` @26
  at unknown location
    @17 := @27
    @15 := @17
    @13 := @15
    @5 := @13
  at 'org/luaj/vm2/LuaString.java' 226
    goto $4
$6
  at 'org/luaj/vm2/LuaValue.java' 3398
    @42 := field org.luaj.vm2.LuaValue.NONE as `Lorg/luaj/vm2/LuaValue;`
    goto $5
$7
  at 'org/luaj/vm2/LuaValue.java' 3399
    @37 := 0
    @43 := @40[@37] as object
    goto $5
$8
  at 'org/luaj/vm2/LuaValue.java' 3400
    @44 := new org.luaj.vm2.Varargs$PairVarargs
    @38 := 0
    @45 := @40[@38] as object
    @39 := 1
    @46 := @40[@39] as object
  at unknown location
    initClass org.luaj.vm2.Varargs$PairVarargs
  at 'org/luaj/vm2/Varargs.java' 568
    nop
    invoke `org.luaj.vm2.Varargs.<init>()V` @44
  at 'org/luaj/vm2/Varargs.java' 569
    field org.luaj.vm2.Varargs$PairVarargs.v1 @44 := @45 as `Lorg/luaj/vm2/LuaValue;`
  at 'org/luaj/vm2/Varargs.java' 570
    field org.luaj.vm2.Varargs$PairVarargs.v2 @44 := @46 as `Lorg/luaj/vm2/Varargs;`
  at 'org/luaj/vm2/LuaValue.java' 3400
    goto $5
$9
  at 'org/luaj/vm2/LuaValue.java' 3401
    @47 := new org.luaj.vm2.Varargs$ArrayVarargs
    @48 := field org.luaj.vm2.LuaValue.NONE as `Lorg/luaj/vm2/LuaValue;`
    invoke `org.luaj.vm2.Varargs$ArrayVarargs.<init>([Lorg/luaj/vm2/LuaValue;Lorg/luaj/vm2/Varargs;)V` @47, @21, @48
    goto $5
$10
  at 'org/luaj/vm2/LuaValue.java' 3401
    @51 := @53
    @20 := @51
  at 'org/luaj/vm2/LuaValue.java' 1519
    @18 := 4
    @21 := newArray `Lorg/luaj/vm2/LuaValue;`[@18]
    @40 := data @21 as object
    @22 := data @21 as object
    @19 := 0
    @22[@19] := @16 as object
    @23 := 1
    @22[@23] := @14 as object
    @24 := 2
    @22[@24] := @12 as object
    @25 := 3
    @22[@25] := @this as object
  at 'org/luaj/vm2/LuaValue.java' 1796
    nop
  at unknown location
    initClass org.luaj.vm2.LuaValue
  at 'org/luaj/vm2/LuaValue.java' 3397
    nop
    @41 := lengthOf @40
    switch @41 case 0 goto $6 case 1 goto $7 case 2 goto $8 else goto $9
$11
  at 'org/luaj/vm2/LuaValue.java' 3357
    @55 := new org.luaj.vm2.LuaError
    @52 := new java.lang.StringBuilder
  at unknown location
    initClass java.lang.StringBuilder
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 28
    nop
    invoke `java.lang.AbstractStringBuilder.<init>()V` @52
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
    invoke `java.lang.AbstractStringBuilder.append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;` @52, @50
  at unknown location
    @56 := @52
  at 'org/luaj/vm2/LuaValue.java' 3357
    @57 := invoke `org.luaj.vm2.LuaNil.typename()Ljava/lang/String;` @16
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
    invoke `java.lang.AbstractStringBuilder.append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder;` @56, @57
  at unknown location
    @58 := @56
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
    @61 := invoke `java.lang.AbstractStringBuilder.toString()Ljava/lang/String;` @58
  at unknown location
    @59 := @61
    initClass org.luaj.vm2.LuaError
  at 'org/luaj/vm2/LuaError.java' 77
    nop
    invoke `java.lang.RuntimeException.<init>(Ljava/lang/String;)V` @55, @59
  at 'org/luaj/vm2/LuaError.java' 78
    @60 := 1
    field org.luaj.vm2.LuaError.level @55 := @60 as I
  at 'org/luaj/vm2/LuaValue.java' 3357
    throw @55
$12
    @53 := phi @64 from $13, @65 from $14
  at 'org/luaj/vm2/LuaValue.java' 3356
    nop
  at 'org/luaj/vm2/LuaNil.java' 80
    nop
    @62 := 1
  at unknown location
    @54 := @62
  at 'org/luaj/vm2/LuaValue.java' 3356
    if @54 == 0 then goto $10 else goto $11
$13
  at 'org/luaj/vm2/LuaValue.java' 3343
    @64 := invokeVirtual `org.luaj.vm2.LuaValue.rawget(Lorg/luaj/vm2/LuaValue;)Lorg/luaj/vm2/LuaValue;` @63, @49
    goto $12
$14
  at 'org/luaj/vm2/LuaValue.java' 3342
    @65 := field org.luaj.vm2.LuaValue.NIL as `Lorg/luaj/vm2/LuaValue;`
    goto $12
$15
  at 'org/luaj/vm2/LuaValue.java' 3342
    @68 := @70
    @16 := @68
  at 'org/luaj/vm2/LuaValue.java' 1519
    nop
  at 'org/luaj/vm2/LuaValue.java' 1986
    nop
    @49 := field org.luaj.vm2.LuaValue.CALL as `Lorg/luaj/vm2/LuaString;`
    @50 := 'attempt to call '
  at 'org/luaj/vm2/LuaValue.java' 3355
    nop
  at 'org/luaj/vm2/LuaValue.java' 3340
    nop
    @63 := invoke `org.luaj.vm2.LuaNil.getmetatable()Lorg/luaj/vm2/LuaValue;` @16
  at 'org/luaj/vm2/LuaValue.java' 3341
    nop
    if @63 !== null then goto $13 else goto $14
$16
  at 'org/luaj/vm2/LuaValue.java' 3357
    @72 := new org.luaj.vm2.LuaError
    @69 := new java.lang.StringBuilder
  at unknown location
    initClass java.lang.StringBuilder
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 28
    nop
  at unknown location
    initClass java.lang.AbstractStringBuilder
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 49
    nop
    @85 := 16
    invoke `java.lang.AbstractStringBuilder.<init>(I)V` @69, @85
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @84 := field java.lang.AbstractStringBuilder.length @69 as I
    invoke `java.lang.StringBuilder.insert(ILjava/lang/String;)Ljava/lang/AbstractStringBuilder;` @69, @84, @67
  at unknown location
    @73 := @69
  at 'org/luaj/vm2/LuaNil.java' 60
    nop
    @186 := 'nil'
  at unknown location
    @74 := @186
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @83 := field java.lang.AbstractStringBuilder.length @73 as I
    invoke `java.lang.StringBuilder.insert(ILjava/lang/String;)Ljava/lang/AbstractStringBuilder;` @73, @83, @74
  at unknown location
    @75 := @73
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 599
    nop
    @79 := new java.lang.String
    @81 := field java.lang.AbstractStringBuilder.buffer @75 as `[C`
    @80 := 0
    @82 := field java.lang.AbstractStringBuilder.length @75 as I
    invoke `java.lang.String.<init>([CII)V` @79, @81, @80, @82
  at unknown location
    @78 := @79
    @76 := @78
    initClass org.luaj.vm2.LuaError
  at 'org/luaj/vm2/LuaError.java' 77
    nop
  at unknown location
    initClass java.lang.RuntimeException
  at 'org/teavm/classlib/java/lang/TRuntimeException.java' 37
    nop
    invoke `java.lang.Exception.<init>(Ljava/lang/String;)V` @72, @76
  at 'org/luaj/vm2/LuaError.java' 78
    @77 := 1
    field org.luaj.vm2.LuaError.level @72 := @77 as I
  at 'org/luaj/vm2/LuaValue.java' 3357
    throw @72
$17
    @70 := phi @88 from $18, @89 from $19
  at 'org/luaj/vm2/LuaValue.java' 3356
    nop
  at 'org/luaj/vm2/LuaNil.java' 80
    nop
    @86 := 1
  at unknown location
    @71 := @86
  at 'org/luaj/vm2/LuaValue.java' 3356
    if @71 == 0 then goto $15 else goto $16
$18
  at 'org/luaj/vm2/LuaValue.java' 3343
    @88 := invokeVirtual `org.luaj.vm2.LuaValue.rawget(Lorg/luaj/vm2/LuaValue;)Lorg/luaj/vm2/LuaValue;` @87, @66
    goto $17
$19
  at 'org/luaj/vm2/LuaValue.java' 3342
    @89 := field org.luaj.vm2.LuaValue.NIL as `Lorg/luaj/vm2/LuaValue;`
    goto $17
$20
  at 'org/luaj/vm2/LuaValue.java' 3342
    @92 := @94
    @14 := @92
  at 'org/luaj/vm2/LuaValue.java' 1491
    nop
  at 'org/luaj/vm2/LuaValue.java' 1986
    nop
    @66 := field org.luaj.vm2.LuaValue.CALL as `Lorg/luaj/vm2/LuaString;`
    @67 := 'attempt to call '
  at 'org/luaj/vm2/LuaValue.java' 3355
    nop
  at 'org/luaj/vm2/LuaValue.java' 3340
    nop
  at 'org/luaj/vm2/LuaNil.java' 85
    nop
    @185 := field org.luaj.vm2.LuaNil.s_metatable as `Lorg/luaj/vm2/LuaValue;`
  at unknown location
    @87 := @185
  at 'org/luaj/vm2/LuaValue.java' 3341
    nop
    if @87 !== null then goto $18 else goto $19
$21
  at 'org/luaj/vm2/LuaValue.java' 3357
    @96 := new org.luaj.vm2.LuaError
    @93 := new java.lang.StringBuilder
  at unknown location
    initClass java.lang.StringBuilder
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 28
    nop
  at unknown location
    initClass java.lang.AbstractStringBuilder
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 49
    nop
    @121 := 16
  at unknown location
    initClass java.lang.AbstractStringBuilder
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 52
    nop
    invoke `java.lang.Object.<init>()V` @93
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 53
    @122 := newArray C[@121]
    field java.lang.AbstractStringBuilder.buffer @93 := @122 as `[C`
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @120 := field java.lang.AbstractStringBuilder.length @93 as I
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
    invoke `java.lang.StringBuilder.insert(ILjava/lang/String;)Ljava/lang/StringBuilder;` @93, @120, @91
  at unknown location
    @97 := @93
  at 'org/luaj/vm2/LuaNil.java' 60
    nop
    @184 := 'nil'
  at unknown location
    @98 := @184
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @119 := field java.lang.AbstractStringBuilder.length @97 as I
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
    invoke `java.lang.StringBuilder.insert(ILjava/lang/String;)Ljava/lang/StringBuilder;` @97, @119, @98
  at unknown location
    @99 := @97
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 599
    nop
    @103 := new java.lang.String
    @105 := field java.lang.AbstractStringBuilder.buffer @99 as `[C`
    @104 := 0
    @106 := field java.lang.AbstractStringBuilder.length @99 as I
  at unknown location
    initClass java.lang.String
  at 'org/teavm/classlib/java/lang/TString.java' 55
    nop
    invoke `java.lang.Object.<init>()V` @103
  at 'org/teavm/classlib/java/lang/TString.java' 56
    @107 := newArray C[@106]
    field java.lang.String.characters @103 := @107 as `[C`
  at 'org/teavm/classlib/java/lang/TString.java' 57
    @108 := 0
  at unknown location
    goto $24
$22
    @102 := @103
    @100 := @102
    initClass org.luaj.vm2.LuaError
  at 'org/luaj/vm2/LuaError.java' 77
    nop
  at unknown location
    initClass java.lang.RuntimeException
  at 'org/teavm/classlib/java/lang/TRuntimeException.java' 37
    nop
  at unknown location
    initClass java.lang.Exception
  at 'org/teavm/classlib/java/lang/TException.java' 34
    nop
    invoke `java.lang.Throwable.<init>(Ljava/lang/String;)V` @96, @100
  at 'org/luaj/vm2/LuaError.java' 78
    @101 := 1
    field org.luaj.vm2.LuaError.level @96 := @101 as I
  at 'org/luaj/vm2/LuaValue.java' 3357
    throw @96
$23
  at 'org/teavm/classlib/java/lang/TString.java' 58
    @113 := data @105 as char
    @111 := field java.lang.String.characters @103 as `[C`
    @116 := data @111 as char
    @112 := @109 + @104
    @114 := @113[@112] as char
    @115 := cast @114 from char to int
    @116[@109] := @115 as char
  at 'org/teavm/classlib/java/lang/TString.java' 57
    @117 := 1
    @118 := @109 + @117
    goto $24
$24
    @109 := phi @108 from $21, @118 from $23
  at 'org/teavm/classlib/java/lang/TString.java' 57
    nop
    @110 := @109 compareTo @106
    if @110 >= 0 then goto $22 else goto $23
$25
    @94 := phi @125 from $26, @126 from $27
  at 'org/luaj/vm2/LuaValue.java' 3356
    nop
  at 'org/luaj/vm2/LuaNil.java' 80
    nop
    @123 := 1
  at unknown location
    @95 := @123
  at 'org/luaj/vm2/LuaValue.java' 3356
    if @95 == 0 then goto $20 else goto $21
$26
  at 'org/luaj/vm2/LuaValue.java' 3343
    @125 := invokeVirtual `org.luaj.vm2.LuaValue.rawget(Lorg/luaj/vm2/LuaValue;)Lorg/luaj/vm2/LuaValue;` @124, @90
    goto $25
$27
  at 'org/luaj/vm2/LuaValue.java' 3342
    @126 := field org.luaj.vm2.LuaValue.NIL as `Lorg/luaj/vm2/LuaValue;`
    goto $25
$28
  at 'org/luaj/vm2/LuaValue.java' 3342
    @12 := @128
  at 'org/luaj/vm2/LuaValue.java' 1457
    nop
  at 'org/luaj/vm2/LuaValue.java' 1986
    nop
    @90 := field org.luaj.vm2.LuaValue.CALL as `Lorg/luaj/vm2/LuaString;`
    @91 := 'attempt to call '
  at 'org/luaj/vm2/LuaValue.java' 3355
    nop
  at 'org/luaj/vm2/LuaValue.java' 3340
    nop
  at 'org/luaj/vm2/LuaNil.java' 85
    nop
    @183 := field org.luaj.vm2.LuaNil.s_metatable as `Lorg/luaj/vm2/LuaValue;`
  at unknown location
    @124 := @183
  at 'org/luaj/vm2/LuaValue.java' 3341
    nop
    if @124 !== null then goto $26 else goto $27
$29
  at 'org/luaj/vm2/LuaValue.java' 3357
    @130 := new org.luaj.vm2.LuaError
    @127 := new java.lang.StringBuilder
  at unknown location
    initClass java.lang.StringBuilder
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 28
    nop
  at unknown location
    initClass java.lang.AbstractStringBuilder
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 49
    nop
    @157 := 16
  at unknown location
    initClass java.lang.AbstractStringBuilder
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 52
    nop
  at unknown location
    initClass java.lang.Object
  at 'org/teavm/classlib/java/lang/TObject.java' 180
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 53
    @158 := newArray C[@157]
    field java.lang.AbstractStringBuilder.buffer @127 := @158 as `[C`
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @156 := field java.lang.AbstractStringBuilder.length @127 as I
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 209
    nop
    invoke `java.lang.AbstractStringBuilder.insert(ILjava/lang/String;)Ljava/lang/AbstractStringBuilder;` @127, @156, @11
  at unknown location
    @131 := @127
  at 'org/luaj/vm2/LuaString.java' 210
    nop
    @182 := 'string'
  at unknown location
    @132 := @182
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 41
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 69
    nop
    @155 := field java.lang.AbstractStringBuilder.length @131 as I
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 209
    nop
    invoke `java.lang.AbstractStringBuilder.insert(ILjava/lang/String;)Ljava/lang/AbstractStringBuilder;` @131, @155, @132
  at unknown location
    @133 := @131
  at 'org/teavm/classlib/java/lang/TStringBuilder.java' 22
    nop
  at 'org/teavm/classlib/java/lang/TAbstractStringBuilder.java' 599
    nop
    @139 := new java.lang.String
    @141 := field java.lang.AbstractStringBuilder.buffer @133 as `[C`
    @140 := 0
    @142 := field java.lang.AbstractStringBuilder.length @133 as I
  at unknown location
    initClass java.lang.String
  at 'org/teavm/classlib/java/lang/TString.java' 55
    nop
  at unknown location
    initClass java.lang.Object
  at 'org/teavm/classlib/java/lang/TObject.java' 180
    nop
  at 'org/teavm/classlib/java/lang/TString.java' 56
    @143 := newArray C[@142]
    field java.lang.String.characters @139 := @143 as `[C`
  at 'org/teavm/classlib/java/lang/TString.java' 57
    @144 := 0
  at unknown location
    goto $32
$30
    @138 := @139
    @134 := @138
    initClass org.luaj.vm2.LuaError
  at 'org/luaj/vm2/LuaError.java' 77
    nop
  at unknown location
    initClass java.lang.RuntimeException
  at 'org/teavm/classlib/java/lang/TRuntimeException.java' 37
    nop
  at unknown location
    initClass java.lang.Exception
  at 'org/teavm/classlib/java/lang/TException.java' 34
    nop
  at unknown location
    initClass java.lang.Throwable
  at 'org/teavm/classlib/java/lang/TThrowable.java' 69
    nop
    @136 := 1
    field java.lang.Throwable.suppressionEnabled @130 := @136 as Z
  at 'org/teavm/classlib/java/lang/TThrowable.java' 70
    @137 := 1
    field java.lang.Throwable.writableStackTrace @130 := @137 as Z
  at 'org/teavm/classlib/java/lang/TThrowable.java' 105
    nop
  at 'org/teavm/classlib/java/lang/TThrowable.java' 72
    field java.lang.Throwable.message @130 := @134 as `Lorg/teavm/classlib/java/lang/TString;`
  at 'org/luaj/vm2/LuaError.java' 78
    @135 := 1
    field org.luaj.vm2.LuaError.level @130 := @135 as I
  at 'org/luaj/vm2/LuaValue.java' 3357
    throw @130
$31
  at 'org/teavm/classlib/java/lang/TString.java' 58
    @149 := data @141 as char
    @147 := field java.lang.String.characters @139 as `[C`
    @152 := data @147 as char
    @148 := @145 + @140
    @150 := @149[@148] as char
    @151 := cast @150 from char to int
    @152[@145] := @151 as char
  at 'org/teavm/classlib/java/lang/TString.java' 57
    @153 := 1
    @154 := @145 + @153
    goto $32
$32
    @145 := phi @144 from $29, @154 from $31
  at 'org/teavm/classlib/java/lang/TString.java' 57
    nop
    @146 := @145 compareTo @142
    if @146 >= 0 then goto $30 else goto $31
$33
    @128 := phi @161 from $34, @162 from $35
  at 'org/luaj/vm2/LuaValue.java' 3356
    nop
  at 'org/luaj/vm2/LuaNil.java' 80
    nop
    @159 := 1
  at unknown location
    @129 := @159
  at 'org/luaj/vm2/LuaValue.java' 3356
    if @129 == 0 then goto $28 else goto $29
$34
  at 'org/luaj/vm2/LuaValue.java' 3343
    @161 := invokeVirtual `org.luaj.vm2.LuaValue.rawget(Lorg/luaj/vm2/LuaValue;)Lorg/luaj/vm2/LuaValue;` @160, @10
    goto $33
$35
  at 'org/luaj/vm2/LuaValue.java' 3342
    @162 := field org.luaj.vm2.LuaValue.NIL as `Lorg/luaj/vm2/LuaValue;`
    goto $33
$36
  at 'org/luaj/vm2/LuaValue.java' 3342
    @187 := 0.0
    initClass org.luaj.vm2.LuaDouble
  at 'org/luaj/vm2/LuaDouble.java' 83
    nop
  at unknown location
    initClass org.luaj.vm2.LuaNumber
  at 'org/luaj/vm2/LuaNumber.java' 35
    nop
  at unknown location
    initClass org.luaj.vm2.LuaValue
  at 'org/luaj/vm2/LuaValue.java' 110
    nop
  at unknown location
    initClass org.luaj.vm2.Varargs
  at 'org/luaj/vm2/Varargs.java' 48
    nop
  at unknown location
    initClass java.lang.Object
  at 'org/teavm/classlib/java/lang/TObject.java' 180
    nop
  at 'org/luaj/vm2/LuaDouble.java' 84
    @188 := @3
  at unknown location
    goto $38
$37
    initClass org.luaj.vm2.LuaInteger
  at 'org/luaj/vm2/LuaInteger.java' 52
    nop
    @170 := 255
    @171 := @164 compareTo @170
    if @171 > 0 then goto $39 else goto $40
$38
    @169 := phi @167 from $36, @168 from $42
  at 'org/luaj/vm2/LuaInteger.java' 52
    @163 := @169
    @4 := @163
    goto $4
$39
  at 'org/luaj/vm2/LuaInteger.java' 52
    @172 := new org.luaj.vm2.LuaInteger
  at unknown location
    initClass org.luaj.vm2.LuaInteger
  at 'org/luaj/vm2/LuaInteger.java' 76
    nop
  at unknown location
    initClass org.luaj.vm2.LuaNumber
  at 'org/luaj/vm2/LuaNumber.java' 35
    nop
  at unknown location
    initClass org.luaj.vm2.LuaValue
  at 'org/luaj/vm2/LuaValue.java' 110
    nop
  at unknown location
    initClass org.luaj.vm2.Varargs
  at 'org/luaj/vm2/Varargs.java' 48
    nop
    invoke `java.lang.Object.<init>()V` @172
  at 'org/luaj/vm2/LuaInteger.java' 77
    field org.luaj.vm2.LuaInteger.v @172 := @164 as I
  at unknown location
    goto $42
$40
  at 'org/luaj/vm2/LuaInteger.java' 52
    @173 := -256
    @174 := @164 compareTo @173
    if @174 <= 0 then goto $39 else goto $41
$41
  at 'org/luaj/vm2/LuaInteger.java' 52
    @175 := field org.luaj.vm2.LuaInteger.intValues as `[Lorg/luaj/vm2/LuaInteger;`
    @178 := data @175 as object
    @176 := 256
    @177 := @164 + @176
    @179 := @178[@177] as object
    goto $42
$42
    @180 := phi @172 from $39, @179 from $41
  at 'org/luaj/vm2/LuaInteger.java' 52
    @168 := @180
  at 'org/luaj/vm2/LuaDouble.java' 79
    goto $38
```

All other optimization levels compile without errors.

**Comment by konsoletyper** [comment]
Do you have any ideas how I can reproduce the issue?

**Comment by mirkosertic** [comment]
I am tracking this down, it is maybe related to a strange class hierarchy in the Lua4J runtime. Give me some time for this, I will try to file an example

**Comment by konsoletyper** [comment]
Least you can do is to provide stack trace

**Comment by mirkosertic** [comment]
Here is the Maven output:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.556 s
[INFO] Finished at: 2017-04-14T14:09:00+02:00
[INFO] Final Memory: 31M/1006M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.5.0-SNAPSHOT:compile (web-client) on project gameengine-teavmrenderer: Unexpected error occured: java.lang.AssertionError: Variable used before definition: @167 at $36 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.teavm:teavm-maven-plugin:0.5.0-SNAPSHOT:compile (web-client) on project gameengine-teavmrenderer: Unexpected error occured
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occured
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:115)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.RuntimeException: java.lang.AssertionError: Variable used before definition: @167 at $36
	at org.teavm.vm.TeaVM.processMethod(TeaVM.java:507)
	at org.teavm.vm.TeaVM.optimize(TeaVM.java:476)
	at org.teavm.vm.TeaVM.build(TeaVM.java:378)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:428)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:110)
	... 23 more
Caused by: java.lang.AssertionError: Variable used before definition: @167 at $36
	at org.teavm.model.util.PhiUpdater.use(PhiUpdater.java:418)
	at org.teavm.model.util.PhiUpdater.renameVariables(PhiUpdater.java:240)
	at org.teavm.model.util.PhiUpdater.updatePhis(PhiUpdater.java:153)
	at org.teavm.model.optimization.ScalarReplacement.performOnce(ScalarReplacement.java:135)
	at org.teavm.model.optimization.ScalarReplacement.optimize(ScalarReplacement.java:49)
	at org.teavm.vm.TeaVM.processMethod(TeaVM.java:501)
	... 27 more
```

**Comment by konsoletyper** [comment]
Looks like I need to reproduce the issue myself. Do you have code in github?
