### ISSUE TITLE
Exception when compiling Ceylon program 

### ISSUE THREAD

**Issue by marciodel** [konsoletyper/teavm#278]
Hi, I'm trying to compile a Ceylon test but the compilation fails. I'm compiling Ceylon to a fatJar and then calling the run_.run() from Java.

```
Caused by: java.lang.IllegalArgumentException: Annotation of type java.lang.Synthetic is already there
        at org.teavm.model.AnnotationContainer.add(AnnotationContainer.java:30)
        at org.teavm.parsing.Parser.parseAnnotations(Parser.java:188)
        at org.teavm.parsing.Parser.parseMethod(Parser.java:61)
        at org.teavm.parsing.Parser.parseClass(Parser.java:88)
        at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:50)
        at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:30)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:110)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:32)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:52)
        at org.teavm.resource.MapperClassHolderSource.get(MapperClassHolderSource.java:36)
        at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:46)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:39)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:27)
        at org.teavm.jso.impl.JSClassProcessor.getMethod(JSClassProcessor.java:1157)
        at org.teavm.jso.impl.JSClassProcessor.processProgram(JSClassProcessor.java:302)
        at org.teavm.jso.impl.JSObjectClassTransformer.transformClass(JSObjectClassTransformer.java:57)
        at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:71)
        at org.teavm.dependency.DependencyClassSource.lambda$get$24(DependencyClassSource.java:51)
        at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:51)
        at org.teavm.dependency.DependencyChecker.createClassDependency(DependencyChecker.java:299)
        at org.teavm.dependency.DependencyChecker.lambda$new$4(DependencyChecker.java:110)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:52)
        at org.teavm.dependency.DependencyChecker.linkClass(DependencyChecker.java:262)
        at org.teavm.dependency.DependencyGraphBuilder$1.create(DependencyGraphBuilder.java:569)
        at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:141)
        at org.teavm.model.instructions.ConstructInstruction.acceptVisitor(ConstructInstruction.java:47)
        at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:189)
        at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:138)
        at org.teavm.dependency.DependencyChecker.lambda$scheduleMethodAnalysis$11(DependencyChecker.java:392)
        at org.teavm.dependency.DependencyChecker.processQueue(DependencyChecker.java:505)
        at org.teavm.dependency.DependencyChecker.processDependencies(DependencyChecker.java:518)
        at org.teavm.vm.TeaVM.build(TeaVM.java:390)
        at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:344)
        at com.edibleday.TeaVMTask.compTeaVM(TeaVMTask.kt:105)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```

**Comment by konsoletyper** [comment]
Looks like TeaVM does not support repeated annotations, which were introduced in Java 8. I don't know where you got this `java.lang.Synthetic` annotation. Can you give me your jar file, so that I could propose you a workaround?

**Comment by marciodel** [comment]
Sure,

The java Main class is very simple:

```
package org.xjsinterop.samples.video;

import org.xjsinterop.dsl.run_;

public class Player {

	public static void main(String[] args) {
		run_.run();
	}
} 

```

The ceylon run function is very simple:


```
"Run the module `org.xjsinterop.dsl`."
shared void run() {
    print("Teste");
}

```


I've renamed the file to jar.zip, because Github rejects .jar file extensions.

[org.xjsinterop.dsl-1.0.0.jar.zip](https://github.com/konsoletyper/teavm/files/1011929/org.xjsinterop.dsl-1.0.0.jar.zip)

**Comment by konsoletyper** [comment]
Looks like this annotation appears on `ceylon/language/List$impl$Patch` class in `<init>` method (i.e. constructor) with signature `(Lceylon/language/List$impl;Lcom/redhat/ceylon/compiler/java/runtime/model/TypeDescriptor;Lceylon/language/List;JJ)V`.
The first parameter of the constructor is marked twice with the annotation called `java/lang/Synthetic`.

Looks like a bug in Ceylon compiler/stdlib. I don't know anything about such annotation, there's `synthetic` modifier indeed, but no such annotation. Also, I have no idea why it's repeated twise.

Anyway, it's a bug (or rather lack of feature) in TeaVM, I'll fix it later. Temporarily you can use workaround. Download TeaVM sources and apply following patch

```
Index: core/src/main/java/org/teavm/model/AnnotationContainer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/src/main/java/org/teavm/model/AnnotationContainer.java	(revision d882fd14a63cc1bd76060b3abf34f85d3b013692)
+++ core/src/main/java/org/teavm/model/AnnotationContainer.java	(revision )
@@ -22,9 +22,6 @@
     private Map<String, AnnotationHolder> annotations = new HashMap<>();
 
     public void add(AnnotationHolder annotation) {
-        if (annotations.containsKey(annotation.getType())) {
-            throw new IllegalArgumentException("Annotation of type " + annotation.getType() + " is already there");
-        }
         annotations.put(annotation.getType(), annotation);
     }
 
```

build TeaVM locally (`mvn install -DskipTests -Dteavm.build.all=false`) and use `0.5.0-SNAPSHOT` version in Maven configuration. This helped me to get working JS file.

**Comment by marciodel** [comment]
Thanks! I really don't know about this java.lang.Synthetic annotation, but several tools refers to it. 
https://android.googlesource.com/platform/tools/idea/+/28d9ee094b1d352884aaf5b66b85b30335165c03/java/compiler/instrumentation-util/src/com/intellij/compiler/notNullVerification/NotNullVerifyingInstrumenter.java

http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftrunk%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2FClassReader.java

http://www.programcreek.com/java-api-examples/index.php?api=org.codehaus.groovy.ast.AnnotationNode

This last one refers to annotations that are not in classpath. Maybe there are more like this one.
