### ISSUE TITLE
Webassembly compiler crash

### ISSUE THREAD

**Issue by salmonb** [konsoletyper/teavm#312]
Hello,

I made a reproducer here: https://github.com/salmonb/teavm-issues (same project as previous issue but with new module wasm-crash-issue which contains the exact same code as the other module but with webassembly compilation target)

I'm getting this error:

`[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.5.1:compile (default) on project wasm-crash-issue: Unexpected error occured: fromIndex(1) > toIndex(0) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.teavm:teavm-maven-plugin:0.5.1:compile (default) on project wasm-crash-issue: Unexpected error occured
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occured
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:111)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at java.util.Collections$UnmodifiableRandomAccessList.subList(Collections.java:1400)
	at org.teavm.backend.wasm.render.WasmBinaryRenderer.renderFunction(WasmBinaryRenderer.java:267)
	at org.teavm.backend.wasm.render.WasmBinaryRenderer.renderCode(WasmBinaryRenderer.java:255)
	at org.teavm.backend.wasm.render.WasmBinaryRenderer.render(WasmBinaryRenderer.java:74)
	at org.teavm.backend.wasm.WasmTarget.emit(WasmTarget.java:383)
	at org.teavm.vm.TeaVM.build(TeaVM.java:385)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:423)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:106)
	... 23 more`

**Comment by konsoletyper** [comment]
Can you provide code example that causes this error?

**Comment by salmonb** [comment]
Yes, this is the github link I provided above (same link as last issue but you can update the project to get the new module that contains the code)

**Comment by konsoletyper** [comment]
Ah, now I see. Sorry
