### ISSUE TITLE
String.format() -  Can't provide name for method as it was not found

### ISSUE THREAD

**Issue by Namek** [konsoletyper/teavm#331]
# The problem

Using `String.format()` function throws `NamingException`. It's an issue to me because I don't use it directly, just some library does.

# Error

> Can't provide name for method as it was not found: java.lang.String.format(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; -> [Help 1]

# Reproduce

So I have generated app using method from documentation (`Getting Started`):

```
mvn -DarchetypeCatalog=local   -DarchetypeGroupId=org.teavm   -DarchetypeArtifactId=teavm-maven-webapp   -DarchetypeVersion=0.5.1 archetype:generate
```

Then slightly modified the `main` function by adding this call:
`String.format(Locale.getDefault(), "omgor");`

# Full code

```java
public class Client {
    public static void main(String[] args) {
        HTMLDocument document = HTMLDocument.current();
        HTMLElement div = document.createElement("div");
        div.appendChild(document.createTextNode("TeaVM generated element"));
        document.getBody().appendChild(div);

        String.format(Locale.getDefault(), "omgor");
    }
}
```

# Stacktrace

```
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin:0.5.1:compile (web-client) on project graphql2elm-web: Unexpected error occured: Error rendering class net.namekdev.graphql2elm.Client. See a cause for details: Can't provide name for method as it was not found: java.lang.String.format(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.teavm:teavm-maven-plugin:0.5.1:compile (web-client) on project graphql2elm-web: Unexpected error occured
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unexpected error occured
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:111)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.teavm.vm.RenderingException: Error rendering class net.namekdev.graphql2elm.Client. See a cause for details
    at org.teavm.backend.javascript.rendering.Renderer.renderMethodBodies (Renderer.java:375)
    at org.teavm.backend.javascript.rendering.Renderer.render (Renderer.java:286)
    at org.teavm.backend.javascript.JavaScriptTarget.emit (JavaScriptTarget.java:269)
    at org.teavm.backend.javascript.JavaScriptTarget.emit (JavaScriptTarget.java:211)
    at org.teavm.vm.TeaVM.build (TeaVM.java:385)
    at org.teavm.tooling.TeaVMTool.generate (TeaVMTool.java:423)
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:106)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.teavm.backend.javascript.codegen.NamingException: Can't provide name for method as it was not found: java.lang.String.format(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
    at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getFullNameFor (DefaultNamingStrategy.java:67)
    at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getFullNameFor (DefaultNamingStrategy.java:55)
    at org.teavm.backend.javascript.rendering.StatementRenderer.visit (StatementRenderer.java:1089)
    at org.teavm.ast.InvocationExpr.acceptVisitor (InvocationExpr.java:50)
    at org.teavm.backend.javascript.rendering.StatementRenderer.visit (StatementRenderer.java:161)
    at org.teavm.ast.AssignmentStatement.acceptVisitor (AssignmentStatement.java:60)
    at org.teavm.backend.javascript.rendering.StatementRenderer.visitStatements (StatementRenderer.java:1382)
    at org.teavm.backend.javascript.rendering.StatementRenderer.visit (StatementRenderer.java:182)
    at org.teavm.ast.SequentialStatement.acceptVisitor (SequentialStatement.java:30)
    at org.teavm.backend.javascript.rendering.Renderer$MethodBodyRenderer.visit (Renderer.java:730)
    at org.teavm.ast.RegularMethodNode.acceptVisitor (RegularMethodNode.java:45)
    at org.teavm.backend.javascript.rendering.Renderer.renderBody (Renderer.java:654)
    at org.teavm.backend.javascript.rendering.Renderer.renderMethodBodies (Renderer.java:372)
    at org.teavm.backend.javascript.rendering.Renderer.render (Renderer.java:286)
    at org.teavm.backend.javascript.JavaScriptTarget.emit (JavaScriptTarget.java:269)
    at org.teavm.backend.javascript.JavaScriptTarget.emit (JavaScriptTarget.java:211)
    at org.teavm.vm.TeaVM.build (TeaVM.java:385)
    at org.teavm.tooling.TeaVMTool.generate (TeaVMTool.java:423)
    at org.teavm.maven.TeaVMCompileMojo.execute (TeaVMCompileMojo.java:106)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by Namek** [comment]
When used the http://teavm.org/sandbox I got output that seems to say something else/more:

```
Native method org.teavm.classlib.impl.unicode.CLDRHelper.getLikelySubtagsMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
Native method org.teavm.classlib.impl.unicode.CLDRHelper.getDefaultLocale$$create()Lorg/teavm/platform/metadata/StringResource; has no implementation
Native method org.teavm.classlib.impl.unicode.CLDRHelper.getDecimalDataMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
Native method org.teavm.classlib.impl.unicode.CLDRHelper.getNumberFormatMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
Native method org.teavm.classlib.impl.currency.CurrencyHelper.getCurrencies$$create()Lorg/teavm/platform/metadata/ResourceArray; has no implementation
Native method org.teavm.classlib.impl.currency.CurrencyHelper.getCountryToCurrencyMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
```

Code:

```
import java.util.*;

public class Main {
    public static void main(String[] args) {
        String.format("asd");
    }
}
```

Full stacktrace:

```
ERROR at Main.java:6 Native method org.teavm.classlib.impl.unicode.CLDRHelper.getLikelySubtagsMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
    at org.teavm.classlib.impl.unicode.CLDRHelper.getLikelySubtagsMap$$create
    at org.teavm.classlib.impl.unicode.CLDRHelper.getLikelySubtagsMap
    at org.teavm.classlib.impl.unicode.CLDRHelper.getLikelySubtags(CLDRHelper.java:31)
    at org.teavm.classlib.impl.unicode.CLDRHelper.resolveCountry(CLDRHelper.java:37)
    at java.util.Currency.getInstance(TCurrency.java:67)
    at java.text.NumberFormat.<init>(TNumberFormat.java:34)
    at java.text.DecimalFormat.<init>(TDecimalFormat.java:60)
    at java.text.NumberFormat.getNumberInstance(TNumberFormat.java:144)
    at java.util.Formatter$FormatWriter.formatDecimalInt(TFormatter.java:342)
    at java.util.Formatter$FormatWriter.formatValue(TFormatter.java:223)
    at java.util.Formatter$FormatWriter.write(TFormatter.java:187)
    at java.util.Formatter.format(TFormatter.java:134)
    at java.util.Formatter.format(TFormatter.java:125)
    at java.lang.String.format(TString.java:658)
ERROR at Main.java:6 Native method org.teavm.classlib.impl.unicode.CLDRHelper.getDefaultLocale$$create()Lorg/teavm/platform/metadata/StringResource; has no implementation
    at org.teavm.classlib.impl.unicode.CLDRHelper.getDefaultLocale$$create
    at org.teavm.classlib.impl.unicode.CLDRHelper.getDefaultLocale
    at java.util.Locale.<clinit>(TLocale.java:70)
    at java.util.Formatter.<init>(TFormatter.java:40)
    at java.lang.String.format(TString.java:658)
ERROR at Main.java:6 Native method org.teavm.classlib.impl.unicode.CLDRHelper.getNumberFormatMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
    at org.teavm.classlib.impl.unicode.CLDRHelper.getNumberFormatMap$$create
    at org.teavm.classlib.impl.unicode.CLDRHelper.getNumberFormatMap
    at org.teavm.classlib.impl.unicode.CLDRHelper.resolveNumberFormat(CLDRHelper.java:173)
    at java.text.NumberFormat.getNumberInstance(TNumberFormat.java:143)
    at java.util.Formatter$FormatWriter.formatDecimalInt(TFormatter.java:342)
    at java.util.Formatter$FormatWriter.formatValue(TFormatter.java:223)
    at java.util.Formatter$FormatWriter.write(TFormatter.java:187)
    at java.util.Formatter.format(TFormatter.java:134)
    at java.util.Formatter.format(TFormatter.java:125)
    at java.lang.String.format(TString.java:658)
ERROR at Main.java:6 Native method org.teavm.classlib.impl.unicode.CLDRHelper.getDecimalDataMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
    at org.teavm.classlib.impl.unicode.CLDRHelper.getDecimalDataMap$$create
    at org.teavm.classlib.impl.unicode.CLDRHelper.getDecimalDataMap
    at org.teavm.classlib.impl.unicode.CLDRHelper.resolveDecimalData(CLDRHelper.java:207)
    at java.text.DecimalFormatSymbols.initData(TDecimalFormatSymbols.java:47)
    at java.text.DecimalFormatSymbols.<init>(TDecimalFormatSymbols.java:43)
    at java.util.Formatter$FormatWriter.formatDecimalInt(TFormatter.java:341)
    at java.util.Formatter$FormatWriter.formatValue(TFormatter.java:223)
    at java.util.Formatter$FormatWriter.write(TFormatter.java:187)
    at java.util.Formatter.format(TFormatter.java:134)
    at java.util.Formatter.format(TFormatter.java:125)
    at java.lang.String.format(TString.java:658)
ERROR at Main.java:6 Native method org.teavm.classlib.impl.currency.CurrencyHelper.getCurrencies$$create()Lorg/teavm/platform/metadata/ResourceArray; has no implementation
    at org.teavm.classlib.impl.currency.CurrencyHelper.getCurrencies$$create
    at org.teavm.classlib.impl.currency.CurrencyHelper.getCurrencies
    at java.util.Currency.initCurrencies(TCurrency.java:44)
    at java.util.Currency.getInstance(TCurrency.java:55)
    at java.util.Currency.getInstance(TCurrency.java:72)
    at java.text.NumberFormat.<init>(TNumberFormat.java:34)
    at java.text.DecimalFormat.<init>(TDecimalFormat.java:60)
    at java.text.NumberFormat.getNumberInstance(TNumberFormat.java:144)
    at java.util.Formatter$FormatWriter.formatDecimalInt(TFormatter.java:342)
    at java.util.Formatter$FormatWriter.formatValue(TFormatter.java:223)
    at java.util.Formatter$FormatWriter.write(TFormatter.java:187)
    at java.util.Formatter.format(TFormatter.java:134)
    at java.util.Formatter.format(TFormatter.java:125)
    at java.lang.String.format(TString.java:658)
ERROR at Main.java:6 Native method org.teavm.classlib.impl.currency.CurrencyHelper.getCountryToCurrencyMap$$create()Lorg/teavm/platform/metadata/ResourceMap; has no implementation
    at org.teavm.classlib.impl.currency.CurrencyHelper.getCountryToCurrencyMap$$create
    at org.teavm.classlib.impl.currency.CurrencyHelper.getCountryToCurrencyMap
    at java.util.Currency.getInstance(TCurrency.java:68)
    at java.text.NumberFormat.<init>(TNumberFormat.java:34)
    at java.text.DecimalFormat.<init>(TDecimalFormat.java:60)
    at java.text.NumberFormat.getNumberInstance(TNumberFormat.java:144)
    at java.util.Formatter$FormatWriter.formatDecimalInt(TFormatter.java:342)
    at java.util.Formatter$FormatWriter.formatValue(TFormatter.java:223)
    at java.util.Formatter$FormatWriter.write(TFormatter.java:187)
    at java.util.Formatter.format(TFormatter.java:134)
    at java.util.Formatter.format(TFormatter.java:125)
    at java.lang.String.format(TString.java:658)
```

**Comment by konsoletyper** [comment]
Please, try recent version (0.6.0-dev-477) from bintray. And note that even the recent version of TeaVM does not fully support `String.format`. I recommend to avoid using this method. You can simply concatenate strings and numbers (preferred way) or use `MessageFormat`.

As for `teavm-javac`, the reason is completely different (you can see it from stacktrace). Java methods responsible for formatting numbers and date/time, rely on locale-specific format strings, which are taken from Unicode CLDR. Unicode CLDR is a large zip file with lots of XML or JSON files, 20+ mb size. The main focus of `teavm-javac` is small download size, so I stripped out CLDR, and still have no idea how to get it back without making `classlib.txt` file (which is 5.2 mb for now) much bigger.

**Comment by Namek** [comment]
Already tried `0.6.0-dev-477` (before posting) - it didn't help.

The issue is it's not my use of `String.format`. It's internal library (ANTLR4 Java runtime) and it actually does it when throwing exceptions. I don't really care about output of this, it could return empty strings. Can I override this somehow?

**Comment by konsoletyper** [comment]
Tried myself with 0.6.0-dev-477 and could not reproduce the issue (build completes without errors). Are you sure you have correct project setup?

**Comment by Namek** [comment]
> Are you sure you have correct project setup?

Indeed, I didn't. Thanks. With the latest version from this repo it worked.  Thank you.

BTW I use this https://github.com/Namek/teavm-gradle-plugin
