### ISSUE TITLE
Java 10 support

### ISSUE THREAD

**Issue by sriharshachilakapati** [konsoletyper/teavm#339]
Just got curious enough to ask, how much support for Java 10 is present at the moment? I really want to try using local variable type inference on the web too.

**Comment by konsoletyper** [comment]
Looks like most of TeaVM works with Java 10. I have only 28 tests fail with TeaVM, all are related to metaprogramming API. However, with TeaVM you can only use Java 10 syntax (e.g. `var`), not Java 10 class library.

**Comment by magick93** [comment]
> not Java 10 class library.

Why can the Java 10 class library not be used?

**Comment by konsoletyper** [comment]
TeaVM does not work with class library from running JRE. There are several reasons:

1. Java class library has many native methods either to interact with operating system or with virtual machine itself. To use OpenJDK class library, TeaVM has to "patch" all corresponding classes and methods. This makes TeaVM dependent on certain JVM implementation and even on certain version.
2. There are many things that can be implemented more efficiently in web if they were specially written for web.
3. Dependency on running JVM would produce different results in different machines, often this is undesirable.

Therefore TeaVM uses its own (incomplete) implementation of Java classes, see [classlib](https://github.com/konsoletyper/teavm/tree/master/classlib/src/main/java/org/teavm/classlib/java) module. These classes were initially forked from Apache Harmony, the only Java implementation that was distributed under Apache 2.0 license. I can't use OpenJDK implementation due to license restrictions. Another reason is I have many patches that I made myself and to stay up-to-date with OpenJDK I have to pull their changed and merge them with my patches.

Anyway, full class library is huge and it's makes no sence to compile it to hundreds of megabytes of JavaScript. TeaVM goal is not running Java applications without recompilation, it's about allowing to write new code in Java that will run both in the server and in the browser.

If you want to use some Java 10 method that is missing in TeaVM, you can ask me to add it. Or you can contribute this method yourself, but please, don't copy/paste OpenJDK code, it's prohibitied by its license.

**Comment by sriharshachilakapati** [comment]
I'm getting an error when I set the Java source version and target version to 10.

~~~groovy
sourceCompatibility = JavaVersion.VERSION_1_10
targetCompatibility = JavaVersion.VERSION_1_10
~~~

The error is this:

~~~
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
        at org.teavm.parsing.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:43)
        at org.teavm.parsing.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:27)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:114)
        at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:28)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:45)
        at org.teavm.parsing.resource.MapperClassHolderSource.get(MapperClassHolderSource.java:32)
        at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:42)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:35)
        at org.teavm.model.PreOptimizingClassHolderSource.get(PreOptimizingClassHolderSource.java:23)
        at org.teavm.dependency.DependencyClassSource.findClass(DependencyClassSource.java:80)
        at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:70)
        at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:47)
        at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:33)
        at org.teavm.model.ClassReaderSourceHelper.resolveMethodImplementation(ClassReaderSourceHelper.java:33)
        at org.teavm.model.ClassReaderSource.resolveImplementation(ClassReaderSource.java:98)
        at org.teavm.model.ClassHolderSource.resolveMutableImplementation(ClassHolderSource.java:37)
        at org.teavm.dependency.DependencyAnalyzer.lambda$new$0(DependencyAnalyzer.java:98)
        at org.teavm.common.CachedMapper.map(CachedMapper.java:45)
        at org.teavm.dependency.DependencyAnalyzer.linkMethod(DependencyAnalyzer.java:382)
        at org.teavm.vm.TeaVM.entryPoint(TeaVM.java:265)
        at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:400)
~~~

However it's working pretty fine if I set them both to 1.8. The same is the issue if I'm running it with 1.9.

I'm on latest TeaVM (0.6.0-dev-529), with Java 10.0.1 on macOS High Sierra 10.13.5.

**Comment by sriharshachilakapati** [comment]
@konsoletyper Can you tell me how to use Java 10's var feature with this? I cannot seem to get it to compile with Java10 compiled class files.
