### ISSUE TITLE
StackOverflowError for array deserialization

### ISSUE THREAD

**Issue by ScraM-Team** [konsoletyper/teavm#351]
I'm trying to deserialize an array, but am getting a StackOverflowError at the "Building JavaScript file" stage.

The code:
```
    List<String> list = new ArrayList<>();
    list.add("one");
    list.add("two");
    
    String strSerialized = JSON.serialize(list).stringify();
    Node nodeStrings = Node.parse(strSerialized);
    List<String> listDeserialized = JSON.deserialize(nodeStrings, List.class);
    window.alert(listDeserialized.get(0));
```

The partial stack trace:

`Building JavaScript file
Output file built with errors
Error calling proxy method org.teavm.flavour.json.JSON.getClassDeserializer(Lorg/teavm/metaprogramming/ReflectClass;)V: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.teavm.metaprogramming.impl.UsageGenerator.emitPermutation(UsageGenerator.java:150)
	at org.teavm.metaprogramming.impl.UsageGenerator.lambda$installProxyEmitter$0(UsageGenerator.java:84)
	at org.teavm.dependency.DependencyChecker.schedulePropagation(DependencyChecker.java:240)
	at org.teavm.dependency.DependencyNode.propagate(DependencyNode.java:99)
	at org.teavm.dependency.DependencyNodeToNodeTransition.consume(DependencyNodeToNodeTransition.java:43)
	at org.teavm.dependency.DependencyChecker.schedulePropagation(DependencyChecker.java:251)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:206)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:211)
	at org.teavm.dependency.DependencyNodeToNodeTransition.consume(DependencyNodeToNodeTransition.java:40)
	at org.teavm.dependency.DependencyChecker.schedulePropagation(DependencyChecker.java:251)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:206)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:211)
	at org.teavm.dependency.DependencyGraphBuilder$1.invokeSpecial(DependencyGraphBuilder.java:627)
	at org.teavm.dependency.DependencyGraphBuilder$1.invoke(DependencyGraphBuilder.java:596)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:182)
	at org.teavm.model.instructions.InvokeInstruction.acceptVisitor(InvokeInstruction.java:69)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:280)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:128)
	at org.teavm.dependency.DependencyChecker.lambda$scheduleMethodAnalysis$10(DependencyChecker.java:399)
	at org.teavm.dependency.DependencyChecker.processQueue(DependencyChecker.java:512)
	at org.teavm.dependency.DependencyChecker.processDependencies(DependencyChecker.java:525)
	at org.teavm.vm.TeaVM.build(TeaVM.java:347)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:423)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:106)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1090)
	at org.teavm.metaprogramming.impl.reflect.ReflectContext.getClass(ReflectContext.java:46)
	at org.teavm.metaprogramming.impl.reflect.ReflectClassImpl.getComponentType(ReflectClassImpl.java:121)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.emitArrayDeserializer(JsonDeserializerEmitter.java:139)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.getClassDeserializer(JsonDeserializerEmitter.java:107)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.emitArrayDeserializer(JsonDeserializerEmitter.java:160)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.getClassDeserializer(JsonDeserializerEmitter.java:107)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.emitArrayDeserializer(JsonDeserializerEmitter.java:160)
	at org.teavm.flavour.json.emit.JsonDeserializerEmitter.getClassDeserializer(JsonDeserializerEmitter.java:107)
`

I think this change might fix it:

Change line 160 of JsonDeserializerEmitter from:

`        Value<? extends JsonDeserializer> itemDeserializer = getClassDeserializer(cls);
`

to

`        Value<? extends JsonDeserializer> itemDeserializer = getClassDeserializer(cls.getComponentType());
`

**Comment by ScraM-Team** [comment]
Awesome, thanks!  Now that I know my was around TeaVM and Flavour better I will report against the right repository next time.  They work great, thanks for all of the hard work behind them.
