### ISSUE TITLE
HashMap.put unsupported?

### ISSUE THREAD

**Issue by devnewton** [konsoletyper/teavm#440]
I try to compile on of [my project](
https://github.com/devnewton/jnuit/tree/teavm) using Teavm. The compiler complains about HashMap.put:

```

[ERROR] Substitutor for bootstrap method java.lang.invoke.LambdaMetafactory.metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; was not found
    at java.util.stream.Node$OfDouble.truncate(Node.java:522)
    at java.util.stream.Node$OfDouble.truncate(Node.java:471)
    at java.util.stream.SliceOps$SliceTask.doTruncate(SliceOps.java:660)
    at java.util.stream.SliceOps$SliceTask.onCompletion(SliceOps.java:640)
    at java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:592)
    at java.util.stream.AbstractTask.compute(AbstractTask.java:328)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
    at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at java.lang.ModuleLayer.toString(ModuleLayer.java:899)
    at java.lang.String.valueOf(String.java:2951)
    at java.lang.AssertionError.<init>(AssertionError.java:74)
    at java.lang.StringUTF16.getChar(StringUTF16.java:67)
    at java.lang.StringUTF16.hashCode(StringUTF16.java:350)
    at java.lang.String.hashCode(String.java:1505)
    at java.util.HashMap.hash(HashMap.java:339)
    at java.util.HashMap.put(HashMap.java:607)
    at im.bci.jnuit.teavm.controls.Keyboard.addKey(Keyboard.java:103)
    at im.bci.jnuit.teavm.controls.Keyboard.<init>(Keyboard.java:15)
    at im.bci.jnuit.teavm.TeavmNuitControls.<init>(TeavmNuitControls.java:43)
    at im.bci.jnuit.teavm.samples.AbstractSample.launch(AbstractSample.java:62)
    at im.bci.jnuit.teavm.samples.HelloWorld.main(HelloWorld.java:45)
```

**Comment by konsoletyper** [comment]
Do you have `teavm-classlib` dependency in your project?

**Comment by devnewton** [comment]
That was it! Thank you!
