### ISSUE TITLE
IntelliJ Plugin: Compile server crashed: IllegalArgumentException: Service not registered: org.teavm.platform.plugin.MetadataRegistration

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#448]
I followed your instructions to create build and run the flavour demo app.
When I launch TeaVM development server in IntelliJ I get this error:
```
ERROR: Compile server crashed
java.lang.IllegalArgumentException: Service not registered: org.teavm.platform.plugin.MetadataRegistration
	at org.teavm.vm.TeaVM.getService(TeaVM.java:795)
	at org.teavm.classlib.impl.JCLPlugin.install(JCLPlugin.java:145)
	at org.teavm.vm.TeaVM.installPlugins(TeaVM.java:787)
	at org.teavm.devserver.CodeServlet.buildOnce(CodeServlet.java:779)
	at org.teavm.devserver.CodeServlet.runTeaVM(CodeServlet.java:673)
	at java.lang.Thread.run(Thread.java:748)
INFO: Build thread complete
```
No custom code - just vanilla maven archetype.
It is running standalone in tomcat though.

Any ideas?

BTW: I also found some links about an Eclipse plugin. I assume this is old/obsolete/dead - correct?

**Comment by konsoletyper** [comment]
Which version TeaVM plugin are you using? Which version of archetype?

**Comment by konsoletyper** [comment]
> BTW: I also found some links about an Eclipse plugin. I assume this is old/obsolete/dead - correct?

Right
