### ISSUE TITLE
RuntimeException: (JavaScript) TypeError: Cannot find function $putFloat in object null@2b1f4d63

### ISSUE THREAD

**Issue by cyberquarks** [konsoletyper/teavm#538]
I managed to run a test for Google FlatBuffers, here: https://github.com/cyberquarks/flatbuffers-demo-teavm/blob/main/src/test/java/MyGame/Sample/FlatbuffersTest.java but it throws this error:

```
Running MyGame.Sample.FlatbuffersTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.694 sec <<< FAILURE!
testFlatBufferBuilder(MyGame.Sample.FlatbuffersTest)  Time elapsed: 3.998 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: (JavaScript) TypeError: Cannot find function $putFloat in object null@2b1f4d63.
    at <JS>.$rt_throw(test.js:173)
    at org.teavm.junit.TestEntryPoint.run(TestEntryPoint.java:34)
    at org.teavm.junit.TestEntryPoint.main(TestEntryPoint.java:44)
    at <JS>.<unknown_function>(test.js:458)
    at <JS>.$rt_startThread(test.js:7838)
    at <JS>.<unknown_function>(test.js:457)
    at <JS>.runMain(test.js:5)
    at org.teavm.junit.HtmlUnitRunStrategy.runTest(HtmlUnitRunStrategy.java:82)
    at org.teavm.junit.TestRunner.runImpl(TestRunner.java:90)
    at org.teavm.junit.TestRunner.lambda$run$2(TestRunner.java:85)
    at org.teavm.junit.TestRunner.lambda$init$0(TestRunner.java:51)
    at java.base/java.lang.Thread.run(Thread.java:834)
Results :
Tests in error: 
  testFlatBufferBuilder(MyGame.Sample.FlatbuffersTest): java.lang.RuntimeException: (JavaScript) TypeError: Cannot find function $putFloat in object null@2b1f4d63.
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

Anyone can give a hint?

ps. the complete runnable test is in the linked code

**Comment by cyberquarks** [comment]
Running with `-Dteavm.junit.optimized=SIMPLE`

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running MyGame.Sample.FlatbuffersTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 6.267 sec <<< FAILURE!
test(MyGame.Sample.FlatbuffersTest)  Time elapsed: 4.02 sec  <<< ERROR!
java.lang.NullPointerException
	at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getRealField(DefaultNamingStrategy.java:162)
	at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getFullNameFor(DefaultNamingStrategy.java:104)
	at org.teavm.backend.javascript.codegen.SourceWriter.appendStaticField(SourceWriter.java:110)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:1207)
	at org.teavm.ast.QualificationExpr.acceptVisitor(QualificationExpr.java:43)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:172)
	at org.teavm.ast.AssignmentStatement.acceptVisitor(AssignmentStatement.java:60)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visitStatements(StatementRenderer.java:1429)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:193)
	at org.teavm.ast.SequentialStatement.acceptVisitor(SequentialStatement.java:30)
	at org.teavm.backend.javascript.rendering.Renderer$MethodBodyRenderer.visit(Renderer.java:941)
	at org.teavm.ast.RegularMethodNode.acceptVisitor(RegularMethodNode.java:45)
	at org.teavm.backend.javascript.rendering.Renderer.renderBody(Renderer.java:832)
	at org.teavm.backend.javascript.rendering.Renderer.renderMethodBodies(Renderer.java:395)
	at org.teavm.backend.javascript.rendering.Renderer.render(Renderer.java:290)
	at org.teavm.backend.javascript.JavaScriptTarget.emit(JavaScriptTarget.java:394)
	at org.teavm.backend.javascript.JavaScriptTarget.emit(JavaScriptTarget.java:319)
	at org.teavm.vm.TeaVM.build(TeaVM.java:419)
	at org.teavm.junit.TeaVMTestRunner.compileTest(TeaVMTestRunner.java:689)
	at org.teavm.junit.TeaVMTestRunner.compileToJs(TeaVMTestRunner.java:598)
	at org.teavm.junit.TeaVMTestRunner.lambda$runChild$3(TeaVMTestRunner.java:303)
	at org.teavm.junit.TeaVMTestRunner.compile(TeaVMTestRunner.java:480)
	at org.teavm.junit.TeaVMTestRunner.runChild(TeaVMTestRunner.java:302)
	at org.teavm.junit.TeaVMTestRunner.run(TeaVMTestRunner.java:198)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
testFlatBufferBuilder(MyGame.Sample.FlatbuffersTest)  Time elapsed: 2.113 sec  <<< ERROR!
java.lang.NullPointerException
	at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getRealField(DefaultNamingStrategy.java:162)
	at org.teavm.backend.javascript.codegen.DefaultNamingStrategy.getFullNameFor(DefaultNamingStrategy.java:104)
	at org.teavm.backend.javascript.codegen.SourceWriter.appendStaticField(SourceWriter.java:110)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:1207)
	at org.teavm.ast.QualificationExpr.acceptVisitor(QualificationExpr.java:43)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:172)
	at org.teavm.ast.AssignmentStatement.acceptVisitor(AssignmentStatement.java:60)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visitStatements(StatementRenderer.java:1432)
	at org.teavm.backend.javascript.rendering.StatementRenderer.visit(StatementRenderer.java:193)
	at org.teavm.ast.SequentialStatement.acceptVisitor(SequentialStatement.java:30)
	at org.teavm.backend.javascript.rendering.Renderer$MethodBodyRenderer.visit(Renderer.java:941)
	at org.teavm.ast.RegularMethodNode.acceptVisitor(RegularMethodNode.java:45)
	at org.teavm.backend.javascript.rendering.Renderer.renderBody(Renderer.java:832)
	at org.teavm.backend.javascript.rendering.Renderer.renderMethodBodies(Renderer.java:395)
	at org.teavm.backend.javascript.rendering.Renderer.render(Renderer.java:290)
	at org.teavm.backend.javascript.JavaScriptTarget.emit(JavaScriptTarget.java:394)
	at org.teavm.backend.javascript.JavaScriptTarget.emit(JavaScriptTarget.java:319)
	at org.teavm.vm.TeaVM.build(TeaVM.java:419)
	at org.teavm.junit.TeaVMTestRunner.compileTest(TeaVMTestRunner.java:689)
	at org.teavm.junit.TeaVMTestRunner.compileToJs(TeaVMTestRunner.java:598)
	at org.teavm.junit.TeaVMTestRunner.lambda$runChild$3(TeaVMTestRunner.java:303)
	at org.teavm.junit.TeaVMTestRunner.compile(TeaVMTestRunner.java:480)
	at org.teavm.junit.TeaVMTestRunner.runChild(TeaVMTestRunner.java:302)
	at org.teavm.junit.TeaVMTestRunner.run(TeaVMTestRunner.java:198)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Results :
Tests in error: 
  test(MyGame.Sample.FlatbuffersTest)
  testFlatBufferBuilder(MyGame.Sample.FlatbuffersTest)
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by ScraM-Team** [comment]
`Cannot find function $putFloat in object null@2b1f4d63.`

This seems like the TeaVM version of a null pointer exception -- It's trying to invoke a method on a null object.

How did you run this?  Perhaps you can enable TeaVM debugging to get more information.

Also, if there is a way to make a smaller test case that could help narrow things down.
