### ISSUE TITLE
Unable to serialize Nested object

### ISSUE THREAD

**Issue by cyberquarks** [konsoletyper/teavm#540]
For an object:

```java
@JsonPersistable
public class NestedObject {
  @JsonPersistable
  public static class Foo {
    private Bar bar = new Bar();
    public Bar getBar() {
      return bar;
    }
    public void setBar(Bar bar) {
      this.bar = bar;
    }
  }
  @JsonPersistable
  public static class Bar {
    public String name = "Anonymous";
    public String getName() {
      return name;
    }
    public void setName(String name) {
      this.name = name;
    }
  }
}
```

And with this serialization code:

```java
System.out.println(JSON.serialize(new NestedObject.Foo()));
```

It throws this error:

```
java.lang.RuntimeException: : (JavaScript) TypeError: Cannot find function $toString in object [object Object].
	at <JS>.$rt_throw(test.js:220)
	at org.teavm.junit.TestEntryPoint.run(TestEntryPoint.java:34)
	at org.teavm.junit.TestEntryPoint.main(TestEntryPoint.java:44)
	at <JS>.<unknown_function>(test.js:570)
	at <JS>.$rt_startThread(test.js:3763)
	at <JS>.<unknown_function>(test.js:569)
	at <JS>.runMain(test.js:5)
	at org.teavm.junit.HtmlUnitRunStrategy.runTest(HtmlUnitRunStrategy.java:83)
	at org.teavm.junit.TestRunner.runImpl(TestRunner.java:90)
	at org.teavm.junit.TestRunner.lambda$run$2(TestRunner.java:85)
	at org.teavm.junit.TestRunner.lambda$init$0(TestRunner.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Using the latest TeaVM package, and Flavour 0.2.1

**Comment by konsoletyper** [comment]
The behaviour is correct. Try to rewrite your code like following:

```java
System.out.println(JSON.serialize(new NestedObject.Foo()).stringify());
```

The reason is that `JSON.serialize` returns native JavaScript object, which does not actually extend `java.lang.Object` (though at compile time all objects do). This is a bit confusing, but repairing this problem would require significant runtime overhead in many cases, so decision was to keep that problem in favour of performance. The rule is: don't call `equals`, `hashCode`, `toString` and other `Object` methods on subtypes of `JSObject`, otherwise you'll get the error like this.
