### ISSUE TITLE
Unknown opcode JSR

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#55]
Ran into this exception trying to convert some code.  (Line numbers may not match up exactly because I added some debugging code).

The opcode is JSR.  

Caused by: java.lang.RuntimeException: Unknown opcode 168 label L422397815
	at org.teavm.parsing.ProgramParser$1.visitJumpInsn(ProgramParser.java:744)
	at org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:88)
	at org.teavm.parsing.ProgramParser.doAnalyze(ProgramParser.java:231)
	at org.teavm.parsing.ProgramParser.parse(ProgramParser.java:101)
	at org.teavm.parsing.Parser.parseMethod(Parser.java:40)
	at org.teavm.parsing.Parser.parseClass(Parser.java:74)
	at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:50)
	at org.teavm.resource.ResourceClassHolderMapper.map(ResourceClassHolderMapper.java:30)
	at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:110)
	at org.teavm.parsing.ClasspathResourceMapper.map(ClasspathResourceMapper.java:32)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:49)
	at org.teavm.resource.MapperClassHolderSource.get(MapperClassHolderSource.java:36)
	at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:46)
	at org.teavm.parsing.ClasspathClassHolderSource.get(ClasspathClassHolderSource.java:29)
	at org.teavm.platform.plugin.ResourceProgramTransformer.transformInvoke(ResourceProgramTransformer.java:79)
	at org.teavm.platform.plugin.ResourceProgramTransformer.transformBasicBlock(ResourceProgramTransformer.java:50)
	at org.teavm.platform.plugin.ResourceProgramTransformer.transformProgram(ResourceProgramTransformer.java:40)
	at org.teavm.platform.plugin.ResourceTransformer.transformClass(ResourceTransformer.java:31)
	at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:68)
	at org.teavm.dependency.DependencyClassSource.access$000(DependencyClassSource.java:33)
	at org.teavm.dependency.DependencyClassSource$1.map(DependencyClassSource.java:41)
	at org.teavm.dependency.DependencyClassSource$1.map(DependencyClassSource.java:39)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:49)
	at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:52)
	at org.teavm.dependency.DependencyChecker.findMethodReader(DependencyChecker.java:284)
	at org.teavm.dependency.DependencyChecker.access$000(DependencyChecker.java:51)
	at org.teavm.dependency.DependencyChecker$1.map(DependencyChecker.java:79)
	at org.teavm.dependency.DependencyChecker$1.map(DependencyChecker.java:77)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:49)
	at org.teavm.dependency.DependencyChecker$3.map(DependencyChecker.java:89)
	at org.teavm.dependency.DependencyChecker$3.map(DependencyChecker.java:87)
	at org.teavm.common.CachedMapper.map(CachedMapper.java:49)
	at org.teavm.dependency.DependencyChecker.linkMethod(DependencyChecker.java:259)
	at org.teavm.dependency.DependencyGraphBuilder$1.invokeSpecial(DependencyGraphBuilder.java:430)
	at org.teavm.dependency.DependencyGraphBuilder$1.invoke(DependencyGraphBuilder.java:419)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:186)
	at org.teavm.model.instructions.InvokeInstruction.acceptVisitor(InvokeInstruction.java:71)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:189)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:59)
	at org.teavm.dependency.DependencyChecker$10.run(DependencyChecker.java:369)
	at org.teavm.dependency.DependencyChecker.processDependencies(DependencyChecker.java:477)
	at org.teavm.vm.TeaVM.build(TeaVM.java:362)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:296)
	at org.teavm.maven.BuildJavascriptMojo.execute(BuildJavascriptMojo.java:256)

**Comment by konsoletyper** [comment]
The JSR instruction has been deprecated since Java 6. Are you using old jar file?

**Comment by shannah** [comment]
The jar is compiled for JDK5.  (We're stuck on 5 right now because we are doing some other conversions to get it running on J2ME, RIM, etc...).

**Comment by shannah** [comment]
But, I just recompiled for 6, then 7, then 8, and I get the same error.  It seems that javac is still using it - unless I'm doing something wrong.

**Comment by konsoletyper** [comment]
I used JSRInlinerAdapter to get rid of JSR opcodes, rather than trying to handle it by myself (https://github.com/konsoletyper/teavm/commit/cff91e03ffa1b396cfcdfee1ff99e269cef98b54). However, I can't check whether it helps, as I can't find any class with JSR opcode. Could you try to build latest TeaVM and run in against your bytecode?

**Comment by shannah** [comment]
That appeared to fix the issue.
