### ISSUE TITLE
unable to build after being forced to update from 0.7.0-dev-1185 to 0.7.0-dev-1196

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#573]
Due to issue #572 I was forced to update my project to teavm version 0.7.0-dev-1196.
However, this now breaks the build:
```
Error:  Method java.util.ResourceBundle.containsKey(Ljava/lang/String;)Z was not found
    at io.github.mmm.ui.spi.UiLocalizerBundle.doLocalize(UiLocalizerBundle.java:51)
    at io.github.mmm.ui.spi.UiLocalizerBundle.localize(UiLocalizerBundle.java:39)
    at io.github.mmm.ui.spi.AbstractUiLocalizer.localizeOrNull(AbstractUiLocalizer.java:153)
    at io.github.mmm.ui.api.UiLocalizer.localizeOrNull(UiLocalizer.java:99)
    at io.github.mmm.ui.api.UiLocalizer.localizeOrNull(UiLocalizer.java:85)
    at io.github.mmm.ui.api.UiLocalizer.localize(UiLocalizer.java:50)
    at io.github.mmm.ui.demo.shared.place.content.ContentController.doEmbed(ContentController.java:57)
    at io.github.mmm.ui.spi.controller.AbstractUiController.embed(AbstractUiController.java:118)
    at io.github.mmm.ui.spi.controller.AbstractUiNavigationManager.navigateRecursive(AbstractUiNavigationManager.java:177)
    at io.github.mmm.ui.spi.controller.AbstractUiNavigationManager.navigateTo(AbstractUiNavigationManager.java:122)
    at io.github.mmm.ui.tvm.controller.TvmNavigationManager.onLocationChange(TvmNavigationManager.java:96)
    at io.github.mmm.ui.tvm.controller.TvmNavigationManager.onPopState(TvmNavigationManager.java:58)
    at io.github.mmm.ui.tvm.controller.TvmNavigationManager$<init>$lambda$_1_0.handleEvent(TvmNavigationManager.java:47)
    at io.github.mmm.ui.tvm.controller.TvmNavigationManager$<init>$lambda$_1_0.handleEvent$exported$0
...
Error:  Failed to execute goal org.teavm:teavm-maven-plugin:0.7.0-dev-1196:compile (web-client) on project mmm-ui-demo-tvm: Unexpected error occurred: Build error -> [Help 1]
```

Any ideas?
According to history the method `containsKey` was always missing:
https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/util/TResourceBundle.java

However, with the old build (still in my local repo) it worked without this error.

**Comment by hohwille** [comment]
This is not a TeaVM regression issue but the method `containsKey` is missing in [TResourceBundle](https://github.com/konsoletyper/teavm/blob/83a53e13bc2c7ae160190c57ac4ac4d39b16992c/classlib/src/main/java/org/teavm/classlib/java/util/TResourceBundle.java) and needs to be added in TeaVM.
