### ISSUE TITLE
Example fails to build with Java 17

### ISSUE THREAD

**Issue by qtxo** [konsoletyper/teavm#581]
I ran the suggested command to install the example:

mvn archetype:generate -DarchetypeGroupId=org.teavm.flavour -DarchetypeArtifactId=teavm-flavour-application -DarchetypeVersion=0.2.1

imported the project in Eclipse 2021-12 but this error shows up in pom.xml:
`
Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @6b96555d
`

**Comment by ScraM-Team** [comment]
@qtxo, can you try this with a newer version of TeaVM?  You might have to get the latest code from github and update the version in the POM file.

**Comment by sanjeyac** [comment]
I had the same issue, try to update the `maven-war-plugin`'s version to 3.3.2 inside the pom.xml

**Comment by ScraM-Team** [comment]
@sanjeyac , the maven-war-plugin tip is helpful, thanks!  

I'm seeing this error:
Caused by: java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
	at org.teavm.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:266)
	at org.teavm.asm.ClassReader.accept(ClassReader.java:683)
	at org.teavm.asm.ClassReader.accept(ClassReader.java:401)
	at org.teavm.metaprogramming.impl.MetaprogrammingClassLoader.checkIfCompileTime(MetaprogrammingClassLoader.java:94)
	at org.teavm.metaprogramming.impl.MetaprogrammingClassLoader.isCompileTimeClass(MetaprogrammingClassLoader.java:57)

I think this line in the TeaVM source needs to be updated from ASM7 to ASM9: https://github.com/konsoletyper/teavm/blob/master/metaprogramming/impl/src/main/java/org/teavm/metaprogramming/impl/MetaprogrammingClassLoader.java#L132
