### ISSUE TITLE
test-server/index.html references non-existing deobfuscator.js ? 

### ISSUE THREAD

**Issue by ulugbekna** [konsoletyper/teavm#591]
Hi, 

I noticed that `index.html` [references](https://github.com/konsoletyper/teavm/blob/b03518c493493792e967f4a20cd8922f3ce56269/tools/junit/src/main/resources/test-server/index.html#L21) `deobfuscator.js` that's not available inside [test-server](https://github.com/konsoletyper/teavm/tree/master/tools/junit/src/main/resources/test-server) dir. Running tests, I get a corresponding NPE, full logs running `run-tests` config in IJ IDEA: 

```java
2022-06-09 13:18:17.394:INFO::main: Logging initialized @5372ms to org.eclipse.jetty.util.log.StdErrLog
2022-06-09 13:18:17.471:INFO:oejs.Server:main: jetty-9.4.38.v20210224; built: 2021-02-24T20:25:07.675Z; git: 288f3cc74549e8a913bf363250b0744f2695b8e6; jvm 11.0.14.1+10-LTS
2022-06-09 13:18:17.508:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2022-06-09 13:18:17.508:INFO:oejs.session:main: No SessionScavenger set, using defaults
2022-06-09 13:18:17.510:INFO:oejs.session:main: node0 Scavenging every 600000ms
2022-06-09 13:18:17.540:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@606442f8{/,null,AVAILABLE}
2022-06-09 13:18:17.567:INFO:oejs.AbstractConnector:main: Started ServerConnector@12cd4439{HTTP/1.1, (http/1.1)}{0.0.0.0:54476}
2022-06-09 13:18:17.568:INFO:oejs.Server:main: Started @5546ms
Running chrome with user data dir: /var/folders/p7/d3r4fnqn3r53pjlskht_q5fh0000gn/T/teavm12431476194764525583teavm
chrome stderr: 
chrome stderr: DevTools listening on ws://127.0.0.1:9222/devtools/browser/b8bc76e3-6e46-4701-ab32-b4cdfc76db3a
requesting /index.html
requesting /client.js
requesting /deobfuscator.js
2022-06-09 13:18:17.971:WARN:oejs.HttpChannel:qtp9937129-34: /deobfuscator.js
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.lambda$getFromCache$1(BrowserRunStrategy.java:293)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.getFromCache(BrowserRunStrategy.java:289)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.service(BrowserRunStrategy.java:251)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
requesting /deobfuscator.js
2022-06-09 13:18:17.996:WARN:oejs.HttpChannel:qtp9937129-16: /deobfuscator.js
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.lambda$getFromCache$1(BrowserRunStrategy.java:293)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.getFromCache(BrowserRunStrategy.java:289)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.service(BrowserRunStrategy.java:251)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
chrome stderr: objc[11845]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa5da09318) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/102.0.5005.61/Libraries/libGLESv2.dylib (0x11f745290). One of the two will be used. Which one is undefined.
requesting /deobfuscator.js
2022-06-09 13:18:18.015:WARN:oejs.HttpChannel:qtp9937129-36: /deobfuscator.js
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.lambda$getFromCache$1(BrowserRunStrategy.java:293)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.getFromCache(BrowserRunStrategy.java:289)
	at org.teavm.junit.BrowserRunStrategy$TestCodeServlet.service(BrowserRunStrategy.java:251)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base/java.lang.Thread.run(Thread.java:829)
chrome stderr: [0609/131818.036813:INFO:CONSOLE(21)] "Uncaught ReferenceError: deobfuscator is not defined", source: http://localhost:54476/client.js (21)
chrome stderr: [0609/131818.039184:INFO:CONSOLE(21)] "Uncaught ReferenceError: deobfuscator is not defined", source: http://localhost:54476/client.js (21)
chrome stderr: [0609/131818.041998:INFO:CONSOLE(21)] "Uncaught ReferenceError: deobfuscator is not defined", source: http://localhost:54476/client.js (21)
chrome stderr: [0609/131818.119170:INFO:CONSOLE(84)] "Uncaught ReferenceError: Cannot access 'lastDeobfuscatorFile' before initialization", source: http://localhost:54476/client.js (84)
chrome stderr: [0609/131818.119224:INFO:CONSOLE(84)] "Uncaught ReferenceError: Cannot access 'lastDeobfuscatorFile' before initialization", source: http://localhost:54476/client.js (84)
chrome stderr: [0609/131818.119561:INFO:CONSOLE(84)] "Uncaught ReferenceError: Cannot access 'lastDeobfuscatorFile' before initialization", source: http://localhost:54476/client.js (84)
```

Am I missing something?

**Comment by konsoletyper** [comment]
There's a module somewhere in the project, that builds this `deobfuscator.js`. You should built this module first (I believe, that existing 'build-teavm-fast' run configuration does this). Anyway, you can disable deobfuscation of stack traces by some system property.

**Comment by ulugbekna** [comment]
Yes, you're right, fixed it, thanks!
