### ISSUE TITLE
TeaVM development server - java.lang.IllegalArgumentException: Unsupported class file major version 59

### ISSUE THREAD

**Issue by claeslundahl** [konsoletyper/teavm#632]
Hi.

I have this project where the source is compiled on source-level 15 and the version of TeaVM is 0.7.0. 

When I build the project, maven wise, it... builds. 

But when I try to use the "TeaVM development server" in IntelliJ it gives me this message:

```
ERROR: Compile server crashed
java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.teavm.asm.ClassReader.<init>(ClassReader.java:195)
	at org.teavm.asm.ClassReader.<init>(ClassReader.java:176)
	at org.teavm.asm.ClassReader.<init>(ClassReader.java:162)
	at org.teavm.asm.ClassReader.<init>(ClassReader.java:283)
	at org.teavm.parsing.resource.ResourceClassHolderMapper.apply(ResourceClassHolderMapper.java:44)
	at org.teavm.parsing.resource.ResourceClassHolderMapper.apply(ResourceClassHolderMapper.java:27)
	at org.teavm.parsing.ClasspathResourceMapper.find(ClasspathResourceMapper.java:161)
	at org.teavm.parsing.ClasspathResourceMapper.apply(ClasspathResourceMapper.java:122)
	at org.teavm.parsing.ClasspathResourceMapper.apply(ClasspathResourceMapper.java:32)
	at org.teavm.model.PreOptimizingClassHolderSource.optimize(PreOptimizingClassHolderSource.java:47)
	at org.teavm.devserver.CodeServlet.lambda$buildOnce$8(CodeServlet.java:756)
	at org.teavm.cache.MemoryCachedClassReaderSource.lambda$getEntry$0(MemoryCachedClassReaderSource.java:83)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at org.teavm.cache.MemoryCachedClassReaderSource.getEntry(MemoryCachedClassReaderSource.java:82)
	at org.teavm.cache.MemoryCachedClassReaderSource.get(MemoryCachedClassReaderSource.java:63)
	at org.teavm.dependency.DependencyClassSource.findClass(DependencyClassSource.java:89)
	at org.teavm.dependency.DependencyClassSource.findAndTransformClass(DependencyClassSource.java:79)
	at org.teavm.dependency.DependencyClassSource.lambda$get$0(DependencyClassSource.java:56)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:56)
	at org.teavm.dependency.DependencyClassSource.get(DependencyClassSource.java:37)
	at org.teavm.vm.TeaVM.entryPoint(TeaVM.java:291)
	at org.teavm.vm.TeaVM.entryPoint(TeaVM.java:317)
	at org.teavm.devserver.CodeServlet.buildOnce(CodeServlet.java:782)
	at org.teavm.devserver.CodeServlet.runTeaVM(CodeServlet.java:673)
	at java.base/java.lang.Thread.run(Thread.java:832)
INFO: Build thread complete
```

Is this because the plugin cannot handle source / binary files from jdk 15? 

It would be pretty nice to be able to use the plugin and at the same time use the good stuff of jdk 15 like textblocks... 

Or do u think there is another error?

**Comment by Ihromant** [comment]
Hi. I had similar issue with Java 17. It is fixed now in 0.7.0-dev-1209 version. In earlier version (last tested was 0.7.0-dev-1207) issue was present. Try to migrate to newest one.

**Comment by Ihromant** [comment]
I mean migrate plugin as well together with teavm.

**Comment by claeslundahl** [comment]
Thanks for your reply, Ihromant. I tried changing the version of teavm to the one you suggested. Unfortunately the build also stopped working after that, not just the development plugin. Maybe something more specific to my project is wrong. Will test with a completely 'clean' teavm project and see which versions of Java work with which version of teavm.
