### ISSUE TITLE
Buggy metaprogramming

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#649]
Let's consider simple code:
```java
public static String proxyObject(Object object) {
        return getProxy(object.getClass()).write(object);
    }

    @Meta
    private static native Proxy getProxy(Class<?> cls);

    private static void getProxy(ReflectClass<?> cls) {
//        Value<Proxy> pr = Metaprogramming.proxy(Proxy.class, (instance, method, args) -> {
//            Value<String> val = Metaprogramming.emit(() -> "abc");
//            Metaprogramming.exit(val::get);
//        });
        Metaprogramming.exit(() -> null);
    }

    private interface Proxy {
        String write(Object object);
    }
```
It works (obviously returns null and then code fails in runtime).
When I uncomment all commented lines I get next stacktrace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.teavm.model.ProgramReader.variableCount()" because "program" is null
	at org.teavm.metaprogramming.impl.AliasFinder.findAliases(AliasFinder.java:36)
	at org.teavm.metaprogramming.impl.CompositeMethodGenerator.addProgram(CompositeMethodGenerator.java:133)
	at org.teavm.metaprogramming.impl.MetaprogrammingImpl.exit(MetaprogrammingImpl.java:127)
	at ua.ihromant.IO.lambda$getProxy$1(IO.java:25)
	at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:304)
	at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:242)
	at ua.ihromant.IO.getProxy(IO.java:23)
	... 17 more

    at ua.ihromant.IO.getProxy
    at ua.ihromant.IO.proxyObject
    at ua.ihromant.IO.debug
    at ua.ihromant.Client.main
```
Still, when I uncomment it in following way:
```java
Value<Proxy> pr = Metaprogramming.proxy(Proxy.class, (instance, method, args) -> {
//            Value<String> val = Metaprogramming.emit(() -> "abc");
//            Metaprogramming.exit(val::get);
});
```
then build hangs forever.
1. Is there any way to understand what is happening? Currently it's impossible to write code more complex than few straightforward reflective calls.
2. How to fix this code to return proxy that does at least something (in this case returns "abc")? Last line in this case would be:
```java
Metaprogramming.exit(pr::get);
```

**Comment by konsoletyper** [comment]
What is the purpose of the presented code? Usually proxy class is an interface and you want Metaprogramming API to create actual instance from scratch. Some proxies *may* delegate to actual instance, but in this case interface class and actual implementation class are different.

**Comment by konsoletyper** [comment]
Also, I have no idea what actual class you pass to `proxyObject`

**Comment by konsoletyper** [comment]
For me the following code works:

```java
    @Test
    public void testProxy() {
        var a = new Abc();
        assertEquals("abc", getProxy(a.getClass()).write(a));
    }

    @Meta
    private static native Proxy getProxy(Class<?> cls);

    private static void getProxy(ReflectClass<?> cls) {
        var pr = proxy(Proxy.class, (instance, method, args) -> {
            var val = emit(() -> "abc");
            exit(() -> val.get());
        });
        Metaprogramming.exit(() -> pr.get());
    }

    private interface Proxy {
        String write(Object object);
    }

    static class Abc {
        String foo() {
            return "qwe";
        }
    }
```

**Comment by konsoletyper** [comment]
I'm afraid `val::get` notation is not yet supported in TeaVM

**Comment by Ihromant** [comment]
I reused your approach. In IDEA i getting the following outofmemery error:
https://ibb.co/SQnZSDc

Generally the reason why I am fighting against metaprogramming is this fact that I am feeling strong pain when working with teavm-flavour-json. I have two options: either to fix somehow existing library (now I am experiencing this issue: https://github.com/konsoletyper/teavm-flavour/issues/76 or to write my own simplified serializer for my needs.
This is the reason why I am creating issues because I'm stuck in both directions in my project.

**Comment by Ihromant** [comment]
Project where you can try to reproduce OOM issue in IDEA:
https://github.com/Ihromant/hexagon/tree/test
branch test

**Comment by konsoletyper** [comment]
Yes, it's expected behaviour. This was not properly documented in `teavm.org`, however since version 0.7.0 a small update was introduced: in `@Meta` method implementation you should check passed `@ReflectClass` somehow (use any mechanism you want: check annotation presence, check class name with regexp, use whitelist, etc) and if class does not pass this check, call `Metaprogramming.unsupportedCase` and return immediately. Otherwise there's a risk that TeaVM will start to create proxies for just generated proxies, which is clearly visible in the debugger if you put breakpoint on `@Meta` method implementation and start Maven build. Also, you can look at ProxyTest in TeaVM source code, which contains useful examples of how to work with proxies.

**Comment by Ihromant** [comment]
Many thanks for your explanation.

**Comment by Ihromant** [comment]
Simple example of working code:
```java
private static void getProxy(ReflectClass<?> cls) {
        if (!Metaprogramming.findClass(Serializable.class).isAssignableFrom(cls)) {
            Metaprogramming.unsupportedCase();
        }
        var pr = Metaprogramming.proxy(Proxy.class, (instance, method, args) -> {
            String name = cls.getName();
            Metaprogramming.exit(() -> name);
        });
        Metaprogramming.exit(() -> pr.get());
    }
```
