### ISSUE TITLE
Incorrect error handling for Metaprogramming

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#653]
Hi. Let's consider simple serializer written by metaprogramming. https://github.com/Ihromant/hexagon/tree/test2 (test 2 branch)
If we revert latest commit ([1eb5392fb4282bf7a263f6dd382f65b46d43e9f9](https://github.com/Ihromant/hexagon/commit/1eb5392fb4282bf7a263f6dd382f65b46d43e9f9)), it sucessfully works and serializes. But when we add simple change that should by be "kind of the same" and just remove code duplication, it fails with next stacktrace:
```
ERROR: Compile server crashed
java.lang.IllegalArgumentException: Index 8 is out of range
	at org.teavm.model.Program.variableAt(Program.java:149)
	at org.teavm.model.util.InstructionCopyReader.copyVar(InstructionCopyReader.java:106)
	at org.teavm.model.util.InstructionCopyReader.invoke(InstructionCopyReader.java:417)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:182)
	at org.teavm.model.instructions.InvokeInstruction.acceptVisitor(InvokeInstruction.java:82)
	at org.teavm.model.BasicBlock$4.read(BasicBlock.java:299)
	at org.teavm.model.util.ProgramUtils.copyBasicBlock(ProgramUtils.java:107)
	at org.teavm.model.util.ProgramUtils.copy(ProgramUtils.java:92)
	at org.teavm.model.util.ModelUtils.copyMethod(ModelUtils.java:75)
	at org.teavm.model.util.ModelUtils.copyClass(ModelUtils.java:46)
	at org.teavm.model.util.ModelUtils.copyClass(ModelUtils.java:63)
	at org.teavm.model.util.ModelUtils.copyClass(ModelUtils.java:59)
	at org.teavm.dependency.DependencyAnalyzer.submitClass(DependencyAnalyzer.java:232)
	at org.teavm.dependency.DependencyAgent.submitClass(DependencyAgent.java:49)
	at org.teavm.metaprogramming.impl.UsageGenerator.emitPermutation(UsageGenerator.java:186)
	at org.teavm.metaprogramming.impl.UsageGenerator.lambda$installProxyEmitter$0(UsageGenerator.java:84)
	at org.teavm.dependency.DependencyAnalyzer.schedulePropagation(DependencyAnalyzer.java:373)
	at org.teavm.dependency.DependencyNode.scheduleMultipleTypes(DependencyNode.java:215)
	at org.teavm.dependency.DependencyNode.propagate(DependencyNode.java:144)
	at org.teavm.dependency.Transition.propagate(Transition.java:63)
	at org.teavm.dependency.Transition.consume(Transition.java:151)
	at org.teavm.dependency.DependencyAnalyzer.processNodeToNodeTransitionQueue(DependencyAnalyzer.java:676)
	at org.teavm.dependency.DependencyAnalyzer.processQueue(DependencyAnalyzer.java:641)
	at org.teavm.dependency.DependencyAnalyzer.processDependencies(DependencyAnalyzer.java:683)
	at org.teavm.vm.TeaVM.build(TeaVM.java:378)
	at org.teavm.devserver.CodeServlet.buildOnce(CodeServlet.java:847)
	at org.teavm.devserver.CodeServlet.runTeaVM(CodeServlet.java:730)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by konsoletyper** [comment]
Fixed. Now TeaVM reports following:

```
[ERROR] Can't get variable from another context
    at ua.ihromant.IO.getProxy(ReflectInfoCache.java:77)
[ERROR] Can't get variable from another context
    at ua.ihromant.IO.getProxy(ReflectInfoCache.java:77)
[ERROR] Can't get variable from another context
    at ua.ihromant.IO.getProxy(ReflectInfoCache.java:77)
[ERROR] Can't get variable from another context
    at ua.ihromant.IO.getProxy(ReflectInfoCache.java:77)
```

Error goes away when I replace calls to `emit` with `lazy` in `ReflectInfoCache`, lines 30-36.

Additionally, I noticed that you are doing aggressive caching of serializers, which is an incorrect approach. Remember, that Metaprogramming API is just a code generation framework, running purely at compile time. If you cache *builders* and reuse them, you end up with these builders applied on every usage, that in turn leads to generation of too much repeated code. Instead, let Metaprogramming do caching for you. Just declare meta method which produces (de)serlializer for given class. Code generator for each class should take field and in order to deserialize it (except for special cases like primitive) should in turn generate call to meta method.
