### ISSUE TITLE
Use teavm from classpath, not from IDEA plugin folder during compilation with IDEA plugin

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#685]
During investigation of https://github.com/konsoletyper/teavm/issues/679 I noticed previously mentioned bug again.
In IDEA I updated teavm plugin 0.9.0-dev-2 -> 0.9.0-dev-3. Went directly into main method for JS client and added lines:
```java
        List<CharSequence> sequences = new ArrayList<>();
        CharSequence stringBuilder = new StringBuilder();
        sequences.add(stringBuilder);
        sequences.add("b");
        sequences.forEach(cs -> System.out.println(cs.isEmpty()));
```
This code compiled in IDEA successfully, but failed in console with obvious reason:
```
[ERROR] Method java.lang.CharSequence.isEmpty()Z was not found
    at ua.ihromant.sod.web.local.Client.lambda$main$0(Client.java:15)
    at ua.ihromant.sod.web.local.Client$main$lambda$_1_0.accept(Client.java:15)
    at ua.ihromant.sod.web.local.Client$main$lambda$_1_0.accept(Client.java:15)
    at java.util.ArrayList.forEach(TArrayList.java:195)
    at ua.ihromant.sod.web.local.Client.main(Client.java:15)
```
This means that IDEA during compilation uses copy of teavm library present in plugin folder, but not teavm from classpath (0.9.0-dev-2 where CharSequence.isEmpty method is missing).

**Comment by konsoletyper** [comment]
Yes, I know about this problem, but it's not that easy to solve. Perhaps I'll fix it at some point in a distant future.

**Comment by Ihromant** [comment]
Wow. Kudos Alexey.

**Comment by konsoletyper** [comment]
But note that this will be available only since version 0.15.0, and will only be backward compatible down to 0.15.0. So with 0.15.0 IDE plugin you won't be able to use 0.14.0 TeaVM. But, for example, you'll be able to use 0.15.0 IDE + 0.16.0 TeaVM and vice versa.

**Comment by Ihromant** [comment]
Sure, I understand, but this is big step in user learning curve and usage convenience.
