### ISSUE TITLE
Broken stacktrace

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#687]
After recent changes, stacktrace is not correctly formed. Example of stacktrace:
```
Uncaught <error: TypeError: Cannot read properties of null (reading 'toString')>
    at $rt_exception (http://localhost:9090/js/classes.js:256:31)
    at $rt_throw (http://localhost:9090/js/classes.js:245:11)
    at $rt_nullCheck (http://localhost:9090/js/classes.js:895:9)
```
It fails no matter what exception was thrown from Java code in this code snippet
```javascript
function $rt_exception(ex) {
    var err = ex.$jsException;
    if (!err) {
        var javaCause = $rt_throwableCause(ex);
        var jsCause = javaCause !== null ? javaCause.$jsException : $rt_globals.undefined;
        var cause = typeof jsCause === "object" ? { cause : jsCause } : $rt_globals.undefined;
        err = new JavaError("Java exception thrown", cause);
        if (typeof $rt_globals.Error.captureStackTrace === "function") {
            $rt_globals.Error.captureStackTrace(err);
        }
        err[$rt_javaExceptionProp] = ex;
        ex.$jsException = err;
        $rt_fillStack(err, ex);
    }
    return err;
}
```
in the line 
```javascript
$rt_globals.Error.captureStackTrace(err);
```
and source maps are not loaded in this case.

**Comment by konsoletyper** [comment]
@Ihromant, could not reproduce. Can you please provide a self-contained example?

**Comment by Ihromant** [comment]
https://github.com/Ihromant/hexagon/tree/test5
Only what I'm doing - throwing exception. Running project in newest IDEA, teavm-0.9.0-dev-3, xubuntu, Chromium browser in incognito mode.
```
Uncaught <error: TypeError: Cannot read properties of null (reading 'toString')>
    at $rt_exception (http://localhost:9090/teavm/classes.js:256:31)
    at $rt_throw (http://localhost:9090/teavm/classes.js:245:11)
    at ui_Client_main (http://localhost:9090/teavm/classes.js:1690:5)
    at http://localhost:9090/teavm/classes.js:598:15
    at $rt_startThread (http://localhost:9090/teavm/classes.js:1891:18)
    at http://localhost:9090/teavm/classes.js:597:9
    at window.$teavm_deobfuscator_callback [as run] (http://localhost:9090/teavm/classes.js:2045:29)
    at Hz (http://localhost:9090/teavm/classes.js.deobfuscator.js:193:412)
    at EC.<anonymous> (http://localhost:9090/teavm/classes.js.deobfuscator.js:30:397)
    at XMLHttpRequest.fn (http://localhost:9090/teavm/classes.js.deobfuscator.js:89:87)
```
Full stacktrace.

**Comment by Ihromant** [comment]
@konsoletyper
