### ISSUE TITLE
Ask for help using teavm

### ISSUE THREAD

**Issue by aetiurf** [konsoletyper/teavm#706]
I am totally a Java newbie, but got a piece of Java code that has to be compiled into wasi-wasm.

I have read through the [docs](https://teavm.org/docs/tooling/gradle.html) and tried using this [repo's code](https://github.com/konsoletyper/tnoodle-example/tree/master) to work.

But I was stuck in step `./gradlew :appRunWar` like this,

```plain
Running TeaVM
Output file built with errors
Classes compiled: 420
Methods compiled: 3541
Class java.util.concurrent.atomic.AtomicIntegerArray was not found
    at com.google.gson.internal.bind.TypeAdapters.<clinit>(TypeAdapters.java:320)
    at com.google.gson.internal.Streams.parse(Streams.java:49)
    at com.google.gson.JsonParser.parseReader(JsonParser.java:102)
    at com.google.gson.JsonParser.parseReader(JsonParser.java:70)
    at com.google.gson.JsonParser.parseString(JsonParser.java:51)
    at org.teavm.samples.TransformMetadata.TransformMetadata.main(TransformMetadata.java:100)
Watching 48 directories to track changes

> Task :generateJavaScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateJavaScript'.
> Errors occurred during TeaVM build

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

Could anyone give me some guidence? Here is the Java source.

```java
package org.teavm.samples.TransformMetadata;

 import com.google.gson.JsonArray;
 import com.google.gson.JsonElement;
 import com.google.gson.JsonObject;
 import com.google.gson.JsonParser;
 
 import java.util.Date;
 import java.text.SimpleDateFormat;
 
 public class TransformMetadata {
    public static final String IMAGE_NAME = "imageName";
    public static final String IMAGE_DOCID = "doc-test";
    public static final String EXTRACTED_METADATA = "extractedMetadata";
    public static final String THUMBNAIL = "thumbnail";
    public static final String EXECUTION_TIME = "executionTime";

     public static JsonObject main(JsonObject args) {
         long currentTime = System.currentTimeMillis();
 
         System.out.println("TransformMetadata invoked");
         System.out.println(args.toString());
 
         Date date = new Date(currentTime);
         String entry_time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(date.getTime());
         JsonArray startTimes = args.getAsJsonArray("startTimes");
         startTimes.add(entry_time);
 
         JsonObject response = new JsonObject();
         JsonObject ret = new JsonObject();
         
         ret.add(IMAGE_NAME, args.get(IMAGE_NAME));
         ret.add("startTimes", startTimes);
 
         JsonArray commTimes = args.getAsJsonArray("commTimes");
         commTimes.add(0);
         ret.add("commTimes", commTimes);
 
         args = args.getAsJsonObject(EXTRACTED_METADATA);
 
         if (args.has("Properties:exif:DateTimeOriginal")) {
             response.add("creationTime", args.get("Properties:exif:DateTimeOriginal"));
         }
         if (args.has("Properties:exif:GPSLatitude") && args.has("Properties:exif:GPSLatitudeRef")
                 && args.has("Properties:exif:GPSLongitude") && args.has("Properties:exif:GPSLongitudeRef")) {
             JsonElement latitude = parseCoordinate(args.get("Properties:exif:GPSLatitude"), args.get("Properties:exif:GPSLatitudeRef"));
             JsonElement longitude = parseCoordinate(args.get("Properties:exif:GPSLongitude"), args.get("Properties:exif:GPSLongitudeRef"));
             JsonObject geo = new JsonObject();
             geo.add("latitude", latitude);
             geo.add("longitude", longitude);
             response.add("geo", geo);
         }
 
         if (args.has("Properties:exif:Make")) {
             response.add("exifMake", args.get("Properties:exif:Make"));
         }
         if (args.has("Properties:exif:Model")) {
             response.add("exifModel", args.get("Properties:exif:Model"));
         }
 
         JsonObject dimensions = new JsonObject();
         dimensions.addProperty("width", Integer.valueOf(args.get("Width").getAsString()));
         dimensions.addProperty("height", Integer.valueOf(args.get("Height").getAsString()));
         response.add("dimensions", dimensions);
 
         response.add("fileSize", args.get("Filesize"));
         response.add("format", args.get("Mime type"));
 
         ret.add(EXTRACTED_METADATA, response);
         return ret;
     }
 
     static JsonElement parseCoordinate(JsonElement coordinate, JsonElement coordinateDircetion)  {
         String[] degreeArray = coordinate.getAsString().split(",")[0].trim().split("/");
         String[] minuteArray = coordinate.getAsString().split(",")[1].trim().split("/");
         String[] secondArray = coordinate.getAsString().split(",")[2].trim().split("/");
 
         JsonObject ret = new JsonObject();
         ret.addProperty("D", (Integer.valueOf(degreeArray[0])) / (Integer.valueOf(degreeArray[1])));
         ret.addProperty("M", (Integer.valueOf(minuteArray[0])) / (Integer.valueOf(minuteArray[1])));
         ret.addProperty("S", (Integer.valueOf(secondArray[0])) / (Integer.valueOf(secondArray[1])));
         ret.add("Direction", coordinateDircetion);
         return ret;
     }
 
     public static void main(String args[])  {
        JsonObject request = JsonParser.parseString(args[0]).getAsJsonObject();
        JsonObject result = main(request);
        System.out.println(result.toString());
     }
 
 }
```

**Comment by pizzadox9999** [comment]
Hi, the thing I suspect to be in your way is that TeaVM only "emulates" only a certain subset of the java standard library. You can view it here: [Supported Classes](https://teavm.org/jcl-report/recent/jcl.html). Under the package `java.util.concurrent.atomic` your class `AtomicIntegerArray ` is listed in red. This should mean that is not supported. But if you have the full source code of the library you are using you can supply that class by yourself. It may not be the best solution but it could potentielly work.

**Comment by aetiurf** [comment]
> Hi, the thing I suspect to be in your way is that TeaVM only "emulates" only a certain subset of the java standard library. You can view it here: [Supported Classes](https://teavm.org/jcl-report/recent/jcl.html). Under the package `java.util.concurrent.atomic` your class `AtomicIntegerArray ` is listed in red. This should mean that is not supported. But if you have the full source code of the library you are using you can supply that class by yourself. It may not be the best solution but it could potentielly work.

Hello~ That's actually what I thought, and thanks so much for you solution!
