### ISSUE TITLE
IDEA compilation fails on 0.9.0-dev-15

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#827]
After recent changes in 0.9.0-dev-15
```
INFO: Starting build
ERROR: Compile server crashed
java.lang.ArithmeticException: / by zero
	at org.teavm.devserver.CodeServlet$ProgressListenerImpl.progressReached(CodeServlet.java:1094)
	at org.teavm.devserver.CodeServlet$ProgressListenerImpl.phaseStarted(CodeServlet.java:1088)
	at org.teavm.vm.TeaVM.reportPhase(TeaVM.java:599)
	at org.teavm.vm.TeaVM.build(TeaVM.java:367)
	at org.teavm.devserver.CodeServlet.buildOnce(CodeServlet.java:847)
	at org.teavm.devserver.CodeServlet.runTeaVM(CodeServlet.java:730)
	at java.base/java.lang.Thread.run(Thread.java:1583)
INFO: Build thread complete
```
on any project in IDEA.

**Comment by Ihromant** [comment]
@konsoletyper what about releasing fixed plugin? It's really a blocker when you can't develop your application.

**Comment by Ihromant** [comment]
Sure I can and already did (replaced .class by fixed .class file using archive manager), but I suppose that after similar advices number of teavm-dev-users (and potential testers/verifiers) could reduce.
